import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../../components/SiteChrome";
import { WeeklyShareActions } from "../../components/WeeklyShareActions";
import { getEnglishResource } from "../../data/english";
import { getResourceBySlug } from "../../data/resources";
import { siteOrigin } from "../../lib/site";

export const metadata: Metadata = {
  title: "4 startup opportunities worth acting on | 2026.07.30 — Pioneer",
  description: "This week: Entrepreneur First, Berkeley SkyDeck, AWS Activate and TechBBQ—with fit, timing and next actions.",
  alternates: { canonical: "/en/weekly", languages: { "zh-CN": "/weekly", en: "/en/weekly" } },
};

const signals = [
  { slug: "entrepreneur-first-london", order: "01", urgency: "5 DAYS LEFT", deadline: "August 4", signal: "FINAL DEADLINE", whyNow: "The final Fall 2026 application window is closing. The program starts with a 12-week company-formation phase in London before a three-month San Francisco phase.", bestFor: "Exceptional individuals ready to build full time whose cofounder, direction or company is not fully formed.", action: ["Write your strongest ability and non-consensus belief", "Explain why you must build now", "Confirm London, San Francisco and visa logistics"], sourceNote: "Deadline, full-time format and both locations checked against EF's official application page." },
  { slug: "berkeley-skydeck-batch-23", order: "02", urgency: "22 DAYS LEFT", deadline: "August 21", signal: "GLOBAL APPLICATION", whyNow: "Batch 23 is now open globally. The six-month program starts November 2, and roughly 20 Cohort teams receive a published $210,000 investment.", bestFor: "Technology teams that can reach a major product milestone within six months and gain real value from Berkeley research and Bay Area networks.", action: ["Test whether Bay Area access creates customer or capital value", "Calculate location, operating and equity costs", "Define one measurable six-month milestone"], sourceNote: "Application dates, duration and investment checked against Berkeley SkyDeck's official page." },
  { slug: "aws-activate", order: "03", urgency: "ONGOING", deadline: "No fixed cohort", signal: "CLOUD CREDITS", whyNow: "AWS currently lists up to $5,000 for Founders and up to $200,000 for provider-backed Portfolio companies. Apply before infrastructure spend accelerates, not after the bill becomes a problem.", bestFor: "Privately held startups founded within ten years, pre-Series B, with clear product or AI milestones for the credits.", action: ["Model 12 months of normal-price cloud spend", "Identify the Founders or Org ID route", "Set credit-expiry and full-price alerts"], sourceNote: "Credit levels, stage limits and application routes checked against the current AWS Activate pages." },
  { slug: "techbbq-2026", order: "04", urgency: "27 DAYS LEFT", deadline: "August 26–27", signal: "NORDIC MARKET", whyNow: "The Copenhagen event is still selling tickets. This is the useful window to identify investors, customers and meetings; waiting until travel week usually produces random networking.", bestFor: "Early teams treating the Nordics as a real customer, talent or fundraising market, especially in AI, climate, industrial or B2B software.", action: ["List ten target firms or institutions", "Pre-book at least six relevant meetings", "Define one verifiable outcome for each meeting"], sourceNote: "Dates, venue and ticket status checked against TechBBQ's official website." },
] as const;

export default function EnglishWeeklyPage() {
  const entries = signals.map((signal) => { const resource = getResourceBySlug(signal.slug); const english = getEnglishResource(signal.slug); if (!resource || !english) throw new Error(`Missing English weekly resource: ${signal.slug}`); return { ...signal, resource, english }; });
  const structuredData = { "@context": "https://schema.org", "@type": "ItemList", name: "Pioneer Weekly Founder Opportunities", dateModified: "2026-07-30", itemListElement: entries.map(({ resource }, i) => ({ "@type": "ListItem", position: i + 1, name: resource.name, url: `${siteOrigin}/en/resources/${resource.slug}` })) };
  return <main>
    <SiteHeader lang="en" languageHref="/weekly" />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <section className="weekly-hero"><div className="weekly-edition"><span>WEEKLY SIGNAL · 002</span><strong>2026.07.30—08.05</strong></div><div className="weekly-hero-copy"><span className="section-index">FOUNDER OPPORTUNITY BRIEF</span><h1>4 opportunities<br /><em>worth acting on now</em></h1><p>Not another link dump: why each opportunity matters now, who it fits and what to finish today.</p></div><aside className="weekly-principle"><span>SELECTION RULE</span><strong>Time-sensitive</strong><strong>Founder-actionable</strong><strong>Officially verifiable</strong><p>Edited July 30, 2026. Recheck the official page before acting.</p></aside></section>
    <section className="weekly-summary" aria-label="Weekly summary"><div><strong>02</strong><span>DEADLINES</span><p>EF · SkyDeck</p></div><div><strong>01</strong><span>ONGOING</span><p>AWS Activate</p></div><div><strong>04</strong><span>ACTIONS</span><p>A checklist for each</p></div></section>
    <section className="weekly-share-band"><div><span className="section-index">SAVE · SHARE · FOLLOW</span><h2>Do not only save it. Give each opportunity a next step.</h2><p>Send it to the right person, add the three dated opportunities to your calendar or follow the next issue through RSS.</p></div><WeeklyShareActions lang="en" /></section>
    <section className="weekly-list">{entries.map(({ resource, english, ...signal }) => <article className="weekly-signal" key={signal.slug}><div className="weekly-signal-number"><span>{signal.order}</span><small>{signal.signal}</small></div><div className="weekly-signal-main"><div className="weekly-deadline"><span>{signal.urgency}</span><strong>{signal.deadline}</strong></div><span className="section-index">{english.kind} · {english.location}</span><h2>{resource.name}</h2><p className="weekly-signal-description">{english.description}</p><div className="weekly-judgment"><div><span>WHY NOW</span><p>{signal.whyNow}</p></div><div><span>BEST FOR</span><p>{signal.bestFor}</p></div></div><a href={signal.slug === "waic-shanghai-2026" ? "/en/waic-2026" : `/en/resources/${signal.slug}`} data-audience-event="weekly:resource" data-audience-target={signal.slug}>Read Pioneer&apos;s full brief <span aria-hidden="true">→</span></a></div><aside className="weekly-action-card"><span>TODAY&apos;S ACTION</span><h3>Finish these three steps</h3><ol>{signal.action.map((item) => <li key={item}>{item}</li>)}</ol><p>{signal.sourceNote}</p><a href={resource.url} target="_blank" rel="noreferrer" data-audience-event="weekly:official" data-audience-target={signal.slug}>Open official page ↗</a></aside></article>)}</section>
    <section className="weekly-next"><span className="section-index light">NEXT ISSUE</span><h2>We will keep filtering the noise.</h2><p>One weekly selection of programs, events and institution changes that deserve founder action.</p><a href="#about">Get the next issue ↓</a></section>
    <SiteFooter lang="en" />
  </main>;
}
