import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../../components/SiteChrome";
import { WeeklyShareActions } from "../../components/WeeklyShareActions";
import { getEnglishResource } from "../../data/english";
import { getResourceBySlug } from "../../data/resources";
import { siteOrigin } from "../../lib/site";

export const metadata: Metadata = {
  title: "4 startup opportunities worth acting on | 2026.07.17 — Pioneer",
  description: "This week: WAIC 2026, Y Combinator, Entrepreneur First and Berkeley SkyDeck—with fit, deadlines and next actions.",
  alternates: { canonical: "/en/weekly", languages: { "zh-CN": "/weekly", en: "/en/weekly" } },
};

const signals = [
  { slug: "waic-shanghai-2026", order: "01", urgency: "THIS WEEKEND", deadline: "July 17–20", signal: "LIVE NOW", whyNow: "The conference is already in its final decision window. Stop collecting agendas: choose one day, one venue cluster and three kinds of people you must meet.", bestFor: "Teams looking for AI customers, partners, investors or embodied-intelligence signals.", action: ["Choose one venue cluster and a one-day route", "List five named people or companies", "End every useful conversation with one next step"], sourceNote: "Dates and venue information checked against official WAIC sources." },
  { slug: "y-combinator", order: "02", urgency: "10 DAYS LEFT", deadline: "July 27 · 8:00 PM PT", signal: "DEADLINE", whyNow: "The on-time Fall 2026 application window is closing. Late applications may be considered, but no longer follow the standard decision timeline.", bestFor: "Full-time early teams with a clear product or technical direction and global fundraising ambition.", action: ["State the user problem in one sentence", "Prepare a product demo and progress evidence", "Explain why this team is unusually suited to solve it"], sourceNote: "YC states on-time applicants should receive a decision by August 28." },
  { slug: "entrepreneur-first-london", order: "03", urgency: "18 DAYS LEFT", deadline: "August 4", signal: "FINAL DEADLINE", whyNow: "EF London Fall 2026 accepts individual founders, beginning with a 12-week company-formation phase in London before a San Francisco phase.", bestFor: "Exceptional individuals ready to build full time whose cofounder, direction or company is not fully formed.", action: ["Write your strongest ability and non-consensus belief", "Explain why you must build now", "Assess the full-time, in-person and cross-city commitment"], sourceNote: "Start, location and deadline checked against EF's official application page." },
  { slug: "berkeley-skydeck-batch-23", order: "04", urgency: "35 DAYS LEFT", deadline: "August 21", signal: "GLOBAL APPLICATION", whyNow: "Batch 23 is open globally. The six-month program starts November 2, with a published $210,000 investment for Cohort companies.", bestFor: "Technology teams aiming to reach a major product milestone or institutional round within six months.", action: ["Test whether Bay Area access creates real customer or capital value", "Calculate location, operating and equity costs", "Define a six-month measurable milestone"], sourceNote: "Timing, investment and participation details checked against Berkeley SkyDeck." },
] as const;

export default function EnglishWeeklyPage() {
  const entries = signals.map((signal) => { const resource = getResourceBySlug(signal.slug); const english = getEnglishResource(signal.slug); if (!resource || !english) throw new Error(`Missing English weekly resource: ${signal.slug}`); return { ...signal, resource, english }; });
  const structuredData = { "@context": "https://schema.org", "@type": "ItemList", name: "Pioneer Weekly Founder Opportunities", dateModified: "2026-07-17", itemListElement: entries.map(({ resource }, i) => ({ "@type": "ListItem", position: i + 1, name: resource.name, url: `${siteOrigin}${resource.slug === "waic-shanghai-2026" ? "/en/waic-2026" : `/en/resources/${resource.slug}`}` })) };
  return <main>
    <SiteHeader lang="en" languageHref="/weekly" />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <section className="weekly-hero"><div className="weekly-edition"><span>WEEKLY SIGNAL · 001</span><strong>2026.07.17—07.23</strong></div><div className="weekly-hero-copy"><span className="section-index">FOUNDER OPPORTUNITY BRIEF</span><h1>4 opportunities<br /><em>worth acting on now</em></h1><p>Not another link dump: why each opportunity matters now, who it fits and what to finish today.</p></div><aside className="weekly-principle"><span>SELECTION RULE</span><strong>Time-sensitive</strong><strong>Founder-actionable</strong><strong>Officially verifiable</strong><p>Edited July 17, 2026. Recheck the official page before acting.</p></aside></section>
    <section className="weekly-summary" aria-label="Weekly summary"><div><strong>01</strong><span>LIVE NOW</span><p>WAIC this weekend</p></div><div><strong>03</strong><span>DEADLINES</span><p>YC · EF · SkyDeck</p></div><div><strong>04</strong><span>ACTIONS</span><p>A checklist for each</p></div></section>
    <section className="weekly-share-band"><div><span className="section-index">SAVE · SHARE · FOLLOW</span><h2>Do not only save it. Give each opportunity a next step.</h2><p>Send it to the right person, add the deadlines to your calendar or follow the next issue through RSS.</p></div><WeeklyShareActions lang="en" /></section>
    <section className="weekly-list">{entries.map(({ resource, english, ...signal }) => <article className="weekly-signal" key={signal.slug}><div className="weekly-signal-number"><span>{signal.order}</span><small>{signal.signal}</small></div><div className="weekly-signal-main"><div className="weekly-deadline"><span>{signal.urgency}</span><strong>{signal.deadline}</strong></div><span className="section-index">{english.kind} · {english.location}</span><h2>{resource.name}</h2><p className="weekly-signal-description">{english.description}</p><div className="weekly-judgment"><div><span>WHY NOW</span><p>{signal.whyNow}</p></div><div><span>BEST FOR</span><p>{signal.bestFor}</p></div></div><a href={signal.slug === "waic-shanghai-2026" ? "/en/waic-2026" : `/en/resources/${signal.slug}`} data-audience-event="weekly:resource" data-audience-target={signal.slug}>Read Pioneer&apos;s full brief <span aria-hidden="true">→</span></a></div><aside className="weekly-action-card"><span>TODAY&apos;S ACTION</span><h3>Finish these three steps</h3><ol>{signal.action.map((item) => <li key={item}>{item}</li>)}</ol><p>{signal.sourceNote}</p><a href={resource.url} target="_blank" rel="noreferrer" data-audience-event="weekly:official" data-audience-target={signal.slug}>Open official page ↗</a></aside></article>)}</section>
    <section className="weekly-next"><span className="section-index light">NEXT ISSUE</span><h2>We will keep filtering the noise.</h2><p>One weekly selection of programs, events and institution changes that deserve founder action.</p><a href="#about">Get the next issue ↓</a></section>
    <SiteFooter lang="en" />
  </main>;
}
