/* eslint-disable @next/next/no-img-element */
import type { Resource } from "../../data/resources";
import { getEnglishResource } from "../../data/english";
import { institutionPresentation, institutionImages, type InstitutionLang } from "../../data/institutionPresentation";
import { resourceFreshness, freshnessLabel } from "../../lib/resourceFreshness";
import { SiteHeader, SiteFooter } from "../SiteChrome";
import { SaveResource } from "../SaveResource";
import { ResourceReport } from "../ResourceReport";
import { OrganizationResearchDetail } from "../OrganizationResearchDetail";
import { InvestmentResearchDetail } from "../InvestmentResearchDetail";
import { DecisionProfileSections } from "../DecisionProfileSections";
import { InstitutionPrograms, InstitutionAnalysis, InstitutionShare } from "./InstitutionControls";
import "./institutions.css";

export function InstitutionDetail({ resource: r, lang = "zh" }: { resource: Resource; lang?: InstitutionLang }) {
  const en = lang === "en", prefix = en ? "/en" : "", t = (zh: string, english: string) => en ? english : zh;
  const d = institutionPresentation(r, lang), photo = institutionImages[r.slug];
  const status = resourceFreshness(r);
  const officialHost = new URL(r.url).hostname.replace(/^www\./, "");
  const sections = [["overview",t("概览","Overview")],["highlights",t("核心资源","Highlights")],...(d.programs.length?[["programs",t("项目与服务","Programs")]]:[]),...(d.cases.length?[["portfolio",t("代表案例","Portfolio")]]:[]),["analysis",t("深度分析","Analysis")],["location",t("地点与联系","Location & contact")],["sources",t("资料来源","Sources")],["similar",t("相似机构","Similar institutions")]];
  return <main className="institution-detail-page"><SiteHeader lang={lang} languageHref={`${en?"":"/en"}/resources/${r.slug}`}/><div className="institution-width"><nav className="institution-breadcrumb" aria-label={t("面包屑","Breadcrumb")}><a href={prefix||"/"}>{t("首页","Home")}</a><span>/</span><a href={`${prefix}/organizations`}>{t("创业机构","Institutions")}</a><span>/</span><span>{r.name}</span></nav>
    <section className={`institution-hero${photo?" has-photo":""}`} aria-labelledby="institution-title">{photo?<img className="institution-hero-image" src={photo.src} alt="" fetchPriority="high"/>:<img className="institution-hero-image institution-earth" src="/home/earth-lights.png" alt=""/>}<div className="institution-hero-shade"/><div className="institution-hero-tools"><div className="institution-save-control"><SaveResource slug={r.slug} lang={lang} showLabel/></div><InstitutionShare lang={lang}/></div><div className="institution-hero-identity"><div className={`institution-mark logo-${r.color}`}>{r.monogram}</div><div><span className="institution-kicker">{d.copy.kind}</span><h1 id="institution-title">{r.name}</h1><p>{d.copy.whyItMatters.split(/[。]/)[0]}</p><div className="institution-hero-location"><span>⌖ {d.copy.location}</span><a href={r.url} target="_blank" rel="noreferrer">{t("访问官网","Visit website")}</a></div></div></div><p className="institution-hero-description">{d.copy.description}</p><div className="institution-hero-tags">{d.copy.tags.slice(0,6).map(x=><span key={x}>{x}</span>)}</div><aside className="institution-hero-note"><span aria-hidden="true">“</span><p>{d.thesis}</p><small>{t("机构画像 · Pioneer 整理","Institution portrait · Pioneer research")}</small></aside>{photo&&<a className="institution-photo-credit" href={photo.source} target="_blank" rel="noreferrer">{photo.credit}</a>}</section>
    <nav className="institution-section-nav" aria-label={t("机构详情导航","Institution detail navigation")}>{sections.map(([id,label])=><a href={`#institution-${id}`} key={id}>{label}</a>)}</nav>
    <div className="institution-layout"><article className="institution-content">
      <section className="institution-panel" id="institution-overview"><header><h2>1. {t("关于","About")} {r.name}</h2><span>{t("基本信息","What it actually is")}</span></header><div className="institution-about"><div><p>{d.copy.overview}</p><p>{d.thesis}</p></div>{photo&&<a href={r.url} target="_blank" rel="noreferrer" className="institution-about-photo"><img src={photo.src} alt={r.name} loading="lazy"/><span>{t("了解机构","Discover the institution")}</span></a>}</div><div className="institution-metrics">{d.metrics.slice(0,4).map((x,i)=><div key={x.label}><span className="institution-metric-icon" aria-hidden="true">{["◎","▧","◈","⌁"][i]}</span><strong>{x.value}</strong><span>{x.label}</span><small>{x.note}</small></div>)}</div></section>
      <section className="institution-panel" id="institution-highlights"><header><h2>2. {t("核心资源与优势","Key highlights")}</h2><span>{t("为什么值得关注","Why it matters")}</span></header><div className="institution-highlights">{d.capabilities.slice(0,4).map((x,i)=><div key={x.label}><span className="institution-line-icon" aria-hidden="true">{["◎","▥","♧","▦"][i]}</span><h3>{x.label}</h3><p>{x.detail}</p><small>{x.boundary}</small></div>)}</div></section>
      {d.programs.length>0&&<section className="institution-panel" id="institution-programs"><header><h2>3. {t("项目与服务","Programs & services")}</h2><span>{t("选择适合当前阶段的入口","Find the right entry point")}</span></header><InstitutionPrograms programs={d.programs.map(p=>({...p,image:photo?.src}))} lang={lang}/></section>}
      {d.cases.length>0&&<section className="institution-panel" id="institution-portfolio"><header><h2>{d.programs.length?"4":"3"}. {t("代表性创业公司","Notable startups")}</h2><span>{t("已整理案例 · 不代表效果保证","Selected examples · not outcome guarantees")}</span></header><div className="institution-portfolio">{d.cases.map(x=><div key={x.name}><span className="institution-company-mark" aria-hidden="true">{x.name.slice(0,2)}</span><h3>{x.name}</h3><p>{x.detail}</p></div>)}</div><p className="institution-caveat">{t("案例用于理解机构生态和长期积累，不能单独证明其支持造成了公司的成功。","Examples illustrate ecosystem experience; they do not establish that an institution caused a company's success.")}</p></section>}
      <section className="institution-panel" id="institution-analysis"><header><h2>{2+Number(d.programs.length>0)+Number(d.cases.length>0)+1}. {t("深度分析","In-depth analysis")}</h2><span>{t("资源、投入与适配条件","Resources, commitment and fit")}</span></header><div className="institution-analysis-layout"><div><InstitutionAnalysis tabs={d.tabs} lang={lang}/></div><aside className="institution-analysis-facts"><h3>{t("判断依据","Decision evidence")}</h3>{d.copy.highlights.slice(0,4).map(x=><div key={x.label}><span>{x.label}</span><strong>{x.value}</strong></div>)}<small>{t("官方资料与编辑判断分别呈现，不使用无依据的数值评分。","Source facts and editorial judgment are presented separately.")}</small></aside></div><h3>{t("申请条件与流程","Access and preparation")}</h3><p className="institution-access">{d.access}</p>{!en&&<details className="institution-full-research"><summary>{t("完整研究档案：支持内容、申请、费用与案例","Full research dossier")}</summary>{d.investor?<InvestmentResearchDetail resource={r} investment={d.investor}/>:d.org&&d.research?<OrganizationResearchDetail resource={r} profile={d.research} organization={d.org}/>:d.research?<DecisionProfileSections profile={d.research} lang={lang} overview={d.copy.overview}/>:null}</details>}</section>
      <section className="institution-panel" id="institution-sources"><header><h2>{t("资料来源与最新安排","Sources & current arrangements")}</h2><span>{r.verified.replace("核验",en?"reviewed":"核验")}</span></header><p>{t("具体项目、投资、费用和参与资格以官方当前资料为准。资料未核验为新闻时，不将其展示为最新动态。","Confirm current programs, investment terms, costs and eligibility with official sources. Research snapshots are not presented as current news.")}</p><div className="institution-source-list">{(r.sources??[{label:d.copy.source,href:r.url}]).map(x=><a key={x.href} href={x.href} target="_blank" rel="noreferrer">{en?new URL(x.href).hostname:x.label}</a>)}</div></section>
    </article><aside className="institution-sidebar"><section className="institution-panel institution-quick"><h2>{t("快速了解","Quick info")}</h2><div className="institution-quick-brand"><div className={`institution-mark logo-${r.color}`}>{r.monogram}</div><div><h3>{r.name}</h3><span>{d.copy.kind}</span><small>{status==="reviewed"?d.copy.status:freshnessLabel(status,lang)}</small></div></div><dl><div><dt>{t("类型","Type")}</dt><dd>{d.copy.kind}</dd></div><div><dt>{t("所在地","Location")}</dt><dd>{d.copy.location}</dd></div><div><dt>{t("官网","Website")}</dt><dd><a href={r.url} target="_blank" rel="noreferrer">{officialHost}</a></dd></div>{d.copy.highlights.slice(0,3).map(x=><div key={x.label}><dt>{x.label}</dt><dd>{x.value}</dd></div>)}<div><dt>{t("最近核验","Last reviewed")}</dt><dd>{r.verified.replace("核验","").trim()}</dd></div></dl><a className="institution-primary" href={r.url} target="_blank" rel="noreferrer">{t("访问官方网站","Visit official website")}</a><div className="institution-sidebar-save"><SaveResource slug={r.slug} lang={lang} showLabel/></div></section>
      <section className="institution-panel" id="institution-location"><header><h2>{t("地点与联系","Locations & contact")}</h2></header><div className="institution-location-card"><span aria-hidden="true">⌖</span><strong>{d.copy.location}</strong><a href={`https://www.openstreetmap.org/search?query=${encodeURIComponent(`${r.name} ${d.copy.location}`)}`} target="_blank" rel="noreferrer">{t("在地图中查找","Find on map")}</a></div>{photo&&<img className="institution-location-photo" src={photo.src} alt={r.name} loading="lazy"/>}<h3>{t("联系机构","Contact")}</h3><p>{t("通过官方渠道确认项目、会面和合作入口。","Use official channels to confirm program, meeting and partnership access.")}</p><a className="institution-contact-link" href={r.url} target="_blank" rel="noreferrer">{officialHost}</a></section>
      <section className="institution-panel" id="institution-similar"><header><h2>{t("相似机构与相关入口","Similar institutions")}</h2><a href={`${prefix}/organizations`}>{t("查看全部","See all")}</a></header><div className="institution-related">{d.related.map(x=><a href={`${prefix}/resources/${x.slug}`} key={x.slug}><span className={`institution-mini-mark logo-${x.color}`}>{x.monogram}</span><span><strong>{x.name}</strong><small>{en?getEnglishResource(x.slug)?.location:x.location}</small></span></a>)}</div></section></aside></div>
    <section className="institution-bottom-banner"><div><span>PIONEER</span><h2>{t("不同的创业者，更开阔的世界。","Different founders. A more open world.")}</h2><p>{t("找到适合你下一步的资源。","Find the resources that fit your next step.")}</p></div><a href={`${prefix}/organizations`}>{t("探索更多机构","Explore institutions")}</a></section></div><ResourceReport resourceKey={r.slug} lang={lang}/><SiteFooter lang={lang}/></main>;
}
