import { getD1 } from "../../db/d1";
import { listCommunity, type CommunityRow } from "../lib/submissionService";
import { communityFreshness } from "../lib/community";
import { CommunityExplorer } from "./CommunityExplorer";
import { SiteFooter, SiteHeader } from "./SiteChrome";
export async function CommunityDirectory({ lang }: { lang: "zh" | "en" }) {
  const en = lang === "en"; let rows: CommunityRow[] = []; let error = false;
  try { rows = await listCommunity(await getD1()); } catch { error = true; }
  return <main><SiteHeader lang={lang} languageHref={en ? "/community" : "/en/community"} /><section className="product-shell"><div className="product-heading"><div><span className="section-index">COMMUNITY RESOURCES</span><h1>{en ? "Resources founders contribute" : "创业者共同发现的资源"}</h1><p>{en ? "Official links and supplied dates are checked. Contributor reasons remain their own views, separate from Pioneer's research briefs." : "这里核验官方链接及所填日期。推荐理由保留贡献者观点，与 Pioneer 深度整理档案分开标注。"}</p></div><a className="product-button" href={en ? "/en/submit" : "/submit"}>{en ? "Recommend a resource" : "推荐资源"}</a></div><section className="product-panel" aria-labelledby="pioneer-community-title"><span className="section-index">PIONEER COMMUNITY</span><h2 id="pioneer-community-title">{en ? "Pioneer Community" : "Pioneer 社区"}</h2><p>{en ? "Welcome to help maintain Pioneer together. We are building a community where founders can share useful resources and keep them accurate and accessible." : "欢迎加入 Pioneer 社区，一起维护我们共同的创业资源社区，让有用的资源更准确、更容易被找到。"}</p><p>{en ? "Contribute startup resources, update information, report broken links, share your experience, or suggest improvements. Whether you are a founder or simply want to help, your contribution is welcome." : "你可以补充创业资源、更新信息、反馈失效链接、分享使用经验，或提出改进建议。无论你是创业者，还是愿意帮忙的朋友，都欢迎一起参与。"}</p><p>{en ? "To join the effort or discuss collaboration, contact:" : "想参与共同维护或交流合作，请联系："} <a href="mailto:haiyunz2145@gmail.com">haiyunz2145@gmail.com</a></p><a className="product-button" href="mailto:haiyunz2145@gmail.com">{en ? "Contact us to contribute" : "联系参与共建"}</a></section>{error ? <p role="alert">{en ? "Resources are temporarily unavailable. Reload to retry." : "资源暂时无法加载，请刷新重试。"}</p> : <CommunityExplorer lang={lang} rows={rows.map(row => ({ slug: row.slug, name: row.name, type: row.resource_type, location: row.location ?? "", stage: row.stage, reason: row.contributor_reason, deadline: row.deadline, checkedAt: row.verified_at.slice(0, 10), freshness: communityFreshness(row) }))} />}</section><SiteFooter lang={lang} /></main>;
}
