"use client";
import { SaveResource } from "./SaveResource";
import { useMemo, useState } from "react";
type Row = { slug: string; name: string; type: string; location: string; stage: string; reason: string; deadline: string | null; checkedAt: string; archived: boolean };
export function CommunityExplorer({ rows, lang }: { rows: Row[]; lang: "zh" | "en" }) {
  const en = lang === "en", prefix = en ? "/en" : "";
  const [query, setQuery] = useState(""), [type, setType] = useState("all"), [stage, setStage] = useState("all"), [showArchive, setShowArchive] = useState(false);
  const visible = useMemo(() => rows.filter(row => (showArchive || !row.archived) && (type === "all" || row.type === type) && (stage === "all" || row.stage === "any" || row.stage === stage) && `${row.name} ${row.reason} ${row.location}`.toLowerCase().includes(query.toLowerCase().trim())), [rows, query, type, stage, showArchive]);
  return <><div className="product-filters"><label>{en ? "Search" : "搜索"}<input value={query} onChange={event => setQuery(event.target.value)} placeholder={en ? "Name, market or need" : "名称、地区或需求"} /></label><label>{en ? "Type" : "类型"}<select value={type} onChange={event => setType(event.target.value)}>{(en ? [["all", "All types"], ["program", "Program"], ["organization", "Institution"], ["event", "Event"], ["startup", "Startup"], ["knowledge", "Knowledge"]] : [["all", "全部类型"], ["program", "开放计划"], ["organization", "机构"], ["event", "活动"], ["startup", "创业项目"], ["knowledge", "公开知识"]]).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>{en ? "Stage" : "阶段"}<select value={stage} onChange={event => setStage(event.target.value)}>{(en ? [["all", "All stages"], ["idea", "Idea"], ["validation", "Validation"], ["traction", "Traction"], ["growth", "Growth"]] : [["all", "全部阶段"], ["idea", "想法"], ["validation", "验证"], ["traction", "早期增长"], ["growth", "规模增长"]]).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><input type="checkbox" checked={showArchive} onChange={event => setShowArchive(event.target.checked)} />{en ? "Include historical windows" : "包含历史窗口"}</label></div><p role="status">{en ? `${visible.length} matching resources` : `${visible.length} 条匹配资源`}</p><div className="product-grid">{visible.map(row => <article className="product-panel" key={row.slug}><span>{row.archived ? (en ? "Historical" : "历史归档") : (en ? "Official link checked" : "官方链接核验")}</span><h2><a href={`${prefix}/community/${row.slug}`}>{row.name}</a></h2><p>{row.location}</p><p>{row.reason}</p><small>{en ? "Contributor's reason" : "贡献者推荐理由"}</small><p>{row.deadline ?? (en ? "No supplied date" : "未提供日期")} · {en ? "Checked" : "核验"} {row.checkedAt}</p><SaveResource slug={row.slug} lang={lang} /></article>)}</div>{visible.length === 0 && <div className="product-empty"><h2>{en ? "No matching resource yet" : "暂时没有匹配资源"}</h2><p>{en ? "Try a different filter or contribute a specific official source." : "尝试调整筛选，或推荐一个具体的官方来源。"}</p></div>}</>;
}
