import { ContentPoints } from "./ContentPoints";
import type { ResourceResearchProfile } from "../data/resourceProfiles";
import type { DecisionLanguage } from "../data/decisionProfiles";

// One view for the complete localized research model; no language-specific tree.
export function DecisionProfileSections({ profile: p, lang, overview, whyItMatters, historical = false }: { profile: ResourceResearchProfile; lang: DecisionLanguage; overview?: string; whyItMatters?: string; historical?: boolean }) {
  const t = (zh: string, en: string) => lang === "en" ? en : zh;
  const fit = { "优先考虑": t("优先考虑", "Prioritize"), "可以考虑": t("可以考虑", "Consider"), "暂不优先": t("暂不优先", "Lower priority") };
  const strength = { "核心": t("核心", "Core"), "强": t("强", "Strong"), "中": t("中", "Moderate"), "有限": t("有限", "Limited") };
  const cost = { "高": t("高", "High"), "中": t("中", "Moderate"), "低": t("低", "Low") };
  return <>
    <section className="detail-section"><span className="detail-index">01</span><div><h2>{t("基本信息", "Operating model and value")}</h2>{overview && <ContentPoints text={overview} lang={lang} />}<p>{p.identity.model}</p><h3>{t("核心价值", "Primary value")}</h3><p>{p.identity.primaryValue}</p><h3>{t("价值发生条件", "Conditions for value")}</h3><p>{p.identity.valueCondition}</p></div></section>
    <section className="detail-section"><span className="detail-index">02</span><div><h2>{t("支持内容与限制", "Capabilities and limits")}</h2><div className="capability-grid">{p.capabilities.map(x => <div className="capability-row" key={x.label}><strong>{x.label}</strong><span className={`capability-level strength-${x.strength}`}>{strength[x.strength]}</span><p>{x.detail}</p></div>)}</div><p className="analysis-caption">{t("能力强弱是 Pioneer 基于官方公开信息做出的定性判断，用于比较资源结构，不是机构排名或结果保证。", "Capability ratings are Pioneer editorial assessments based on public official information, for comparing resource structure; they are not rankings or guarantees.")}</p></div></section>
    <section className="detail-section"><span className="detail-index">03</span><div><h2>{t("提供内容", "What you actually get")}</h2><div className="offer-detail-grid">{p.offers.map(x => <div className="offer-detail-card" key={x.title}><h3>{x.title}</h3><p>{x.includes}</p><div><b>{t("对创业者的价值", "Founder value")}</b><p>{x.founderValue}</p></div></div>)}</div></div></section>
    <section className="detail-section"><span className="detail-index">04</span><div><h2>{t("申请方式", "Entry paths")}</h2><div className="entry-path-list">{p.entryPaths.map((x, i) => <div className="entry-path" key={x.title}><span>0{i+1}</span><div><h3>{x.title}</h3><p>{x.forWhom}</p><p>{x.prepare}</p></div></div>)}</div></div></section>
    <section className="detail-section"><span className="detail-index">05</span><div><h2>{t("适合阶段", "Stage fit")}</h2><div className="stage-fit-table">{p.stageFit.map(x => <div key={x.stage}><strong>{x.stage}</strong><span className={`fit-badge fit-${x.fit}`}>{fit[x.fit]}</span><p>{x.reason}</p></div>)}</div></div></section>
    <section className="detail-section"><span className="detail-index">06</span><div><h2>{t("费用与投入", "Costs and trade-offs")}</h2><div className="cost-map-grid">{p.costs.map(x => <div className="cost-map-card" key={x.label}><div><strong>{x.label}</strong><span className={`cost-level cost-${x.level}`}>{cost[x.level]}</span></div><p>{x.detail}</p></div>)}</div></div></section>
    <section className="detail-section"><span className="detail-index">07</span><div><h2>{t("申请前确认事项", "Due diligence")}</h2><div className="diligence-list">{p.diligence.map((x, i) => <div key={x}><span>Q{i+1}</span><p>{x}</p></div>)}</div></div></section>
    <section className="detail-section"><span className="detail-index">08</span><div><h2>{historical ? t("用于复盘与下一届准备", "Review and prepare for a future edition") : t("建议准备步骤", "Founder playbook")}</h2><div className="research-playbook">{p.playbook.map((x, i) => <div key={x.title}><span>0{i+1}</span><div><small>{x.phase}</small><h3>{x.title}</h3><p>{x.action}</p></div><strong>{t("产出：", "Output: ")}{x.output}</strong></div>)}</div></div></section>
    <section className="detail-section"><span className="detail-index">09</span><div><h2>{t("适合人群与替代选择", "Compare before deciding")}</h2>{whyItMatters && <ContentPoints text={whyItMatters} lang={lang} />}<div className="comparison-grid"><div className="comparison-choose"><span>{t("适合情况", "Choose when")}</span><p>{p.comparison.chooseWhen}</p></div><div className="comparison-avoid"><span>{t("不适合情况", "Avoid when")}</span><p>{p.comparison.avoidWhen}</p></div><div className="comparison-with"><span>{t("可比较的资源", "Alternatives")}</span><p>{p.comparison.compareWith}</p></div></div></div></section>
  </>;
}
