"use client";
import { useRef, useState } from "react";
export function EventCalendarActions({ slug, available, lang }: {slug:string;available:boolean;lang:"zh"|"en"}) {
  const en = lang === "en", dialog = useRef<HTMLDialogElement>(null), [alarm,setAlarm] = useState("7");
  const href = `${en ? "/en" : ""}/resources/${slug}/calendar.ics`;
  return <div className="event-calendar-actions">{available ? <><a href={href}>{en ? "Add to my calendar ↓" : "加入我的日历 ↓"}</a><button type="button" onClick={()=>dialog.current?.showModal()}>{en ? "Choose a calendar reminder" : "设置日历提醒"}</button></> : <p>{en ? "Calendar unavailable: this edition has ended or its dates need rechecking." : "本届已结束或日期待核验，暂不提供日历与提醒。"}</p>}
    <dialog ref={dialog} className="event-reminder-dialog" aria-labelledby="event-reminder-title"><h2 id="event-reminder-title">{en ? "Import a reminder into your calendar" : "将提醒导入你的日历"}</h2><p>{en ? "Downloading does not activate an alert. Import the file and confirm notification settings in your calendar app. Date-only alerts follow your calendar timezone." : "下载不会自动启用提醒。请导入文件，并在日历应用中确认通知设置。全天活动提醒按你的日历时区处理。"}</p><label>{en ? "Remind me before the event" : "活动开始前提醒"}<select value={alarm} onChange={e=>setAlarm(e.target.value)}><option value="7">{en ? "7 days before" : "提前 7 天"}</option><option value="1">{en ? "1 day before" : "提前 1 天"}</option></select></label><a href={`${href}?alarm=${alarm}`}>{en ? "Download reminder calendar ↓" : "下载带提醒的日历 ↓"}</a><button type="button" onClick={()=>dialog.current?.close()}>{en ? "Close" : "关闭"}</button></dialog>
  </div>;
}
export function EventBudget({ lang }: {lang:"zh"|"en"}) {
  const en=lang==="en";
  const [values,setValues]=useState(["","","","","" ]), [currency,setCurrency]=useState("USD"),[days,setDays]=useState("");
  const labels=en ? ["Tickets","Travel","Lodging","Booth / extra access","Other costs"] : ["门票","差旅","住宿","展位 / 额外通行","其他费用"];
  const total=values.reduce((sum,x)=>sum+(Number(x)||0),0);
  return <div className="event-budget"><h3>{en ? "Estimate your own investment" : "算一下你自己的投入"}</h3><p>{en ? "Your estimate, not an official quote. Use one currency for every item; values stay on this page." : "这是你的预算，不是官方报价。各项请使用同一币种，填写内容仅留在当前页面。"}</p><label>{en ? "Currency" : "币种"}<select value={currency} onChange={e=>setCurrency(e.target.value)}>{["USD","CNY","EUR","SGD","GBP"].map(x=><option key={x}>{x}</option>)}</select></label><div className="event-budget-inputs">{labels.map((label,i)=><label key={label}>{label}<input type="number" min="0" max="100000000" step="any" inputMode="decimal" value={values[i]} onChange={e=>{const next=[...values];next[i]=String(Math.max(0,Math.min(100000000,Number(e.target.value)||0)));setValues(next);}} placeholder="0" /></label>)}<label>{en ? "Team person-days incl. preparation" : "团队总人天（含准备）"}<input type="number" min="0" value={days} onChange={e=>setDays(String(Math.max(0,Number(e.target.value)||0)))} placeholder="0"/></label></div><output aria-live="polite">{en ? "Estimated cash investment" : "预计现金投入"} <strong>{currency} {total.toLocaleString(en ? "en-US":"zh-CN",{maximumFractionDigits:2})}</strong>{days && <span> · {days} {en ? "person-days" : "人天"}</span>}</output><p>{en ? "Set a return threshold: qualified meetings, pilots, follow-up commitments or usable market evidence. Attendance alone is not a return." : "设定回报门槛：有效会面、试点意向、承诺的下一步或可用的市场证据。到场本身不算回报。"}</p></div>;
}
