/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type { Resource } from "../data/resources";
import { resources } from "../data/resources";
import { getEnglishResource } from "../data/english";
import { getResourceProfile } from "../data/resourceProfiles";
import { resourceFreshness, freshnessLabel } from "../lib/resourceFreshness";
import { SiteHeader, SiteFooter } from "./SiteChrome";
import { SaveResource } from "./SaveResource";
import { ResourceReport } from "./ResourceReport";
import { EventCalendarActions, EventBudget } from "./EventDecisionTools";
import { eventCalendarDates } from "../lib/eventCalendar";
import { disruptDecision, eventRoles } from "../data/eventDecisions";
import { ResourceCard } from "./ResourceCard";

export function EventDecisionDetail({ resource: r, lang = "zh" }: { resource: Resource; lang?: "zh" | "en" }) {
  const en = lang === "en", t = (zh: string, english: string) => en ? english : zh;
  const copy = en ? getEnglishResource(r.slug)! : r;
  const profile = getResourceProfile(r.slug);
  const historical = resourceFreshness(r) === "historical";
  const tc = r.slug === "techcrunch-disrupt-2026";
  const prefix = en ? "/en" : "";
  const reviewed = resourceFreshness(r) === "reviewed";
  const calendarAvailable = reviewed && Boolean(eventCalendarDates(r));
  const related = [...(r.relatedSlugs ?? (tc ? ["slush-2026", "y-combinator", "greylock"] : [])).map(slug => resources.find(x=>x.slug===slug)).filter((x): x is Resource => Boolean(x)), ...resources.filter(x=>x.type==="event")].filter((x,i,rows)=>x.slug!==r.slug && resourceFreshness(x)!=="historical" && rows.findIndex(y=>y.slug===x.slug)===i).slice(0,3);
  return <main className="event-decision-page">
    <SiteHeader lang={lang} languageHref={`${en ? "" : "/en"}/resources/${r.slug}`} />
    <section className={`event-decision-hero${tc ? " event-disrupt-hero" : ""}`}>
      {tc && <img className="event-hero-photo" src="/events/disrupt-audience.webp" alt="" width="2048" height="1363" />}
      <div className="event-hero-inner"><nav className="event-breadcrumb" aria-label={t("面包屑", "Breadcrumb")}><a href={prefix || "/"}>{t("首页", "Home")}</a><span>›</span><a href={`${prefix}/events`}>{t("创业活动", "Events")}</a><span>›</span><span>{r.name}</span></nav>
        <div className="event-hero-copy"><span className="event-eyebrow">{copy.kind} · FOUNDER DECISION</span><h1>{tc ? <>TechCrunch<br/>Disrupt 2026</> : r.name}</h1><p>{copy.description}</p><div className="event-hero-meta"><strong>{copy.highlights.find(x => /日期|Dates/.test(x.label))?.value ?? copy.timing}</strong><span>{tc ? "Moscone West · San Francisco, USA" : copy.location}</span></div><div className="event-tags">{copy.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div>
        {tc && <a className="event-image-credit" href={r.url} target="_blank" rel="noreferrer">{t("TechCrunch 官方往届现场图", "Past-edition photo · TechCrunch") } ↗</a>}
      </div>
    </section>
    <div className="event-decision-layout"><article>
      <div className="event-fact-strip">{(tc ? [{ label:t("主办方预计参会", "Organizer attendance forecast"),value:"10,000+" },{label:t("活动时长", "Event duration"),value:t("3 天", "3 days")},{label:t("举办城市", "Host city"),value:"San Francisco"},{label:t("参赛申请", "Competition application"),value:t("已关闭", "Closed")} ] : copy.highlights.slice(0,4).map(f=> /状态|Status/.test(f.label) && !reviewed ? {...f,value:freshnessLabel(resourceFreshness(r),lang)} : f)).map(f => <div key={f.label}><strong>{f.value}</strong><span>{f.label}</span></div>)}</div>
      <nav className="event-section-nav" aria-label={t("活动决策导航", "Event decision navigation")}>{[["verdict",t("是否值得", "Verdict")],["overview",t("活动简介", "Overview")],["content",t("活动内容", "Program")],["fit",t("适合谁", "Fit")],["paths",t("参与方式", "Entry paths")],["costs",t("投入与回报", "Costs")],["playbook",t("参会准备", "Playbook")]].map(([id,label]) => <a key={id} href={`#event-${id}`}>{label}</a>)}</nav>
      <section id="event-verdict" className="event-verdict"><span className="event-eyebrow">PIONEER VERDICT · {t("编辑判断", "Editorial judgment")}</span><h2>{historical ? t("本届已结束，用于复盘与下一届准备", "This edition has ended. Use it to plan the next one.") : t("带着具体目标去，才值得投入。", "Bring a specific outcome worth the trip.")}</h2><div className="event-verdict-grid"><div><h3>{t("最大价值", "Primary value")}</h3><p>{en ? copy.whyItMatters : profile?.identity.primaryValue ?? copy.whyItMatters}</p></div><div><h3>{t("最适合谁", "Best fit")}</h3><p>{copy.bestFor[0]}</p></div><div><h3>{t("主要限制", "Main constraint")}</h3><p>{copy.considerations[0]}</p></div></div></section>
      <section id="event-overview" className="event-prose"><span className="event-eyebrow">01 / UNDERSTAND</span><h2>{t("活动简介", "What the event is")}</h2><p>{copy.overview}</p></section>
      <section id="event-content" className="event-prose"><span className="event-eyebrow">02 / VALUE</span><h2>{t("为什么值得关注", "What founders can gain")}</h2><div className="event-value-grid">{(en ? [{label:"Relevant people",detail:copy.whyItMatters},{label:"Targeted meetings",detail:"Book conversations around a concrete customer, funding or partnership objective."},{label:"Market evidence",detail:"Test your product narrative against real questions and objections."},{label:"Follow-through",detail:"A useful conversation needs an owner, a next step and a date."}] : profile?.capabilities ?? []).map((x,i) => <div key={x.label}><span>0{i+1}</span><h3>{x.label}</h3><p>{x.detail}</p></div>)}</div><h2>{t("活动内容", "Program and founder use cases")}</h2><div className="event-module-grid">{tc && disruptDecision.modules[lang].map(x => <div key={x.title}><h3>{x.title}</h3><p>{x.value}</p></div>)}{(!tc && en ? [{title:"Sessions & program",founderValue:"Confirm this edition’s official agenda; choose sessions that answer your current operating questions."},{title:"Meeting opportunities",founderValue:"Check pass access and matchmaking eligibility before booking."},{title:"Product feedback",founderValue:"Use relevant conversations to test your demo and market assumptions."}] : tc ? [] : profile?.offers ?? []).map(x => <div key={x.title}><h3>{x.title}</h3><p>{x.founderValue}</p>{!en && "includes" in x && <p>{x.includes}</p>}</div>)}</div></section>
      <section id="event-fit" className="event-prose"><span className="event-eyebrow">03 / FIT</span><h2>{t("适合谁", "Who should consider it")}</h2><ul>{copy.bestFor.map(x => <li key={x}>{x}</li>)}</ul><div className="event-role-list">{eventRoles(lang).map(x => <div key={x.role}><h3>{x.role}</h3><strong>{x.fit}</strong><p>{x.focus}</p></div>)}</div><h3>{t("先核对这些限制", "Check these constraints")}</h3><ul>{copy.considerations.map(x => <li key={x}>{x}</li>)}</ul></section>
      <section id="event-paths" className="event-prose"><span className="event-eyebrow">04 / ENTRY</span><h2>{historical ? t("历史参与路径", "Review the Past Window") : t("选择你的参与方式", "Choose your entry path")}</h2><div className="event-module-grid">{tc && disruptDecision.paths[lang].map(x => <div key={x.title}><span className="event-path-status">{historical ? t("历史路径 · 本届已结束", "Archived path · edition ended") : !reviewed ? t("需重新核验 · 上次记录：", "Recheck · last recorded: ")+x.status : x.status}</span><h3>{x.title}</h3><p>{x.forWhom}</p><p>{x.prepare}</p><a href={x.href} target="_blank" rel="noreferrer">{t("查看该路径官方说明", "Read official path details")} ↗</a></div>)}{(!tc && en ? [{title:"Attend",forWhom:"A relevant founder, investor or operator with a specific meeting goal.",prepare:"Check current ticket categories, access and refund terms."},{title:"Showcase or competition",forWhom:"A team with a reliable product demo.",prepare:"Separate applications and deadlines apply. A ticket does not grant a booth or pitch slot."}] : tc ? [] : profile?.entryPaths ?? []).map(x => <div key={x.title}><h3>{x.title}</h3><p>{x.forWhom}</p><p>{x.prepare}</p></div>)}</div></section>
      <section className="event-prose"><h2>{t("出发前的决策检查", "Before committing")}</h2><ul>{(en ? ["Can you name ten relevant people or organizations to meet?", "Which result within 30 days would justify this investment?", "Have you checked separate ticket, showcase and competition requirements?"] : profile?.diligence ?? []).map(x=><li key={x}>{x}</li>)}</ul></section>
      <section id="event-costs" className="event-prose"><span className="event-eyebrow">05 / RETURN</span><h2>{t("费用与投入", "Costs and trade-offs")}</h2><p>{t("门票只是总成本的一部分。把差旅、住宿、准备时间和会后跟进都算进去，再与直接拜访客户等替代方案比较。", "Tickets are only part of the cost. Include travel, lodging, preparation and follow-up; compare the trip with direct customer visits.")}</p>{tc && <p className="event-ticket-note">{t("2026.10.06 官方页面快照：Attendee $949 / Founder $999 / Investor $1,099（美元）。票价、税费和权益以结算页为准；不含差旅或展位。", "Official page snapshot, October 6, 2026: Attendee $949 / Founder $999 / Investor $1,099 (USD). Confirm taxes, access and current pricing at checkout; travel and booths are separate.")}</p>}{!en && profile?.costs.map(x => <div className="event-cost-row" key={x.label}><h3>{x.label}</h3><p>{x.detail}</p></div>)}<EventBudget lang={lang}/></section>
      <section id="event-playbook" className="event-prose"><span className="event-eyebrow">06 / FOUNDER PLAYBOOK</span><h2>{t("把参会变成一项有结果的任务", "Turn attendance into a measurable task")}</h2><p>{t("标准准备节奏如下。如果已不足三周，先确认交通与资格，再集中预约少量目标会面；不要因为临近开幕就仓促投入。", "Use this preparation rhythm. If fewer than three weeks remain, confirm travel and access first, then focus on a few targeted meetings.")}</p><div className="event-timeline">{(en ? [{phase:"6 weeks before",title:"Choose an outcome",action:"Select one primary goal and set a budget and success threshold."},{phase:"3 weeks before",title:"Book the right meetings",action:"Research 30 prospects, prioritize 10 and prepare a short demo."},{phase:"On site",title:"Capture evidence",action:"Record needs, blockers, decision makers and agreed next steps."},{phase:"Within 72 hours",title:"Follow up",action:"Send individual follow-ups and track conversion over 30 days."}] : profile?.playbook.map((x,i) => i === 0 ? {...x,phase:"会前 6 周"} : x) ?? []).map(x => <div key={x.phase}><span>{x.phase}</span><h3>{x.title}</h3><p>{x.action}</p>{"output" in x && <small>{t("交付物：", "Output: ")}{x.output}</small>}</div>)}</div></section>
      <section className="event-final-advice"><span className="event-eyebrow">PIONEER 建议 / RECOMMENDATION</span><h2>{t("先约到人，再决定行程。", "Secure the meetings before committing to the trip.")}</h2><p>{copy.editorialNote}</p><p>{t("这是编辑建议，不是融资、曝光或商业回报保证。", "This is editorial guidance, not a promise of investment, coverage or commercial results.")}</p></section>
      <section id="event-sources" className="event-prose"><span className="event-eyebrow">OFFICIAL SOURCES / {t("事实来源", "FACTS")}</span><h2>{t("官方资料与核验边界", "Sources and review boundaries")}</h2><p>{r.verified} · {t("时间、票价和申请状态来自以下来源。参会价值、角色建议与行动计划属于 Pioneer 编辑判断。其他活动的细节保持各自原有核验日期，未统一更新为本日。", "Dates, prices and application status are factual source snapshots. Value assessments, role recommendations and playbooks are Pioneer editorial guidance. Other editions retain their own review dates.")}</p><div className="event-source-links">{(tc ? disruptDecision.sources : r.sources ?? [{label:copy.source,href:r.url}]).map(x=><a key={x.href} href={x.href} target="_blank" rel="noreferrer">{x.label} ↗</a>)}</div></section>
      <section className="event-prose"><h2>{t("相关资源", "Related resources")}</h2><div className="resource-grid">{related.map(x => <ResourceCard key={x.id} resource={x} lang={lang} />)}</div></section>
    </article><aside className="event-action-sidebar"><div className="event-action-card"><span className="event-state">{reviewed ? copy.status : freshnessLabel(resourceFreshness(r),lang)}</span><h2>{r.name}</h2><p>{copy.highlights.find(x => /日期|Dates/.test(x.label))?.value ?? copy.timing}</p><p>{tc ? "Moscone West · San Francisco, USA" : copy.location}</p>{historical && <p>{t("本届活动或行动窗口已结束。原官网可能已切换到新一届。", "This edition or action window has ended. The website may now show a new edition.")}</p>}<a className="event-primary-action" href={r.url} target="_blank" rel="noreferrer">{historical ? t("查看历史官方来源", "View historical official source") : t("访问官网，核对参与资格", "Check eligibility on the official site")} ↗</a><SaveResource slug={r.slug} lang={lang}/><EventCalendarActions slug={r.slug} available={calendarAvailable} lang={lang}/><div className="event-side-tags">{copy.tags.map(x => <span key={x}>{x}</span>)}</div><a className="event-source-anchor" href="#event-sources">{t("查看官方来源与核验说明", "View official sources and review notes")} ↓</a><div className="event-sidebar-related"><h3>{t("继续比较", "Compare alternatives")}</h3>{related.slice(0,2).map(x=><a key={x.slug} href={`${prefix}/resources/${x.slug}`}>{x.name} <span aria-hidden="true">→</span></a>)}</div><small>{r.verified} · {t("日期、票种与申请入口可能变化", "Dates, passes and application paths may change")}</small></div></aside></div>
    <ResourceReport resourceKey={r.slug} lang={lang}/><SiteFooter lang={lang}/>
  </main>;
}
