"use client";
import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { ARCHIVE_EVENT, clearWorkspaceData, downloadWorkspace, hasLegacyWorkspace, importLegacyWorkspace, initializeWorkspace, readLegacyWorkspace, refreshWorkspace, saveProject, updateWorkspace, workspaceError, workspaceSnapshot } from "../lib/founderArchive";
import { emptyWorkspace, type FounderGoal, type FounderStage, type WorkspaceState } from "../lib/workspaceModel";
export type WorkspaceResource = { slug: string; name: string; type: string; location: string; timing: string; status: string; verified: string; fit: string[]; cautions: string[]; href: string };
export type WorkspaceGuide = { slug: string; title: string; number: string };
const stages = { zh: { idea: "想法探索", validation: "用户与产品验证", traction: "早期增长", growth: "规模增长" }, en: { idea: "Idea", validation: "Validation", traction: "Traction", growth: "Growth" } };
const goalLabels = { zh: { customers: "获得客户", product: "验证产品", funding: "资金与融资", team: "组建团队", learning: "改进判断" }, en: { customers: "Find customers", product: "Validate product", funding: "Funding", team: "Build team", learning: "Improve decisions" } };
const defaultProject = { name: "", oneLine: "", targetUser: "", currentRisk: "", nextAction: "", stage: "idea" as FounderStage, goals: [] as FounderGoal[] };
const guideByStage: Record<FounderStage, string[]> = { idea: ["find-the-real-problem", "first-user-interview"], validation: ["define-your-mvp", "find-your-first-ten-users", "test-your-pricing"], traction: ["close-your-first-sales", "measure-retention-and-pmf", "build-your-startup-metrics"], growth: ["build-your-startup-metrics", "hire-your-first-employee", "prepare-your-fundraising-process"] };
const guideByGoal: Record<FounderGoal, string[]> = { customers: ["find-your-first-ten-users", "close-your-first-sales"], product: ["first-user-interview", "define-your-mvp"], funding: ["decide-whether-to-fundraise", "prepare-your-fundraising-process"], team: ["test-your-cofounder", "hire-your-first-employee"], learning: ["learn-from-startup-failures"] };
export function FounderWorkspace({ lang, catalog, guides, signedIn, accountLabel }: { lang: "zh" | "en"; catalog: WorkspaceResource[]; guides: WorkspaceGuide[]; signedIn: boolean; accountLabel: string }) {
  const en = lang === "en", prefix = en ? "/en" : "";
  const [state, setState] = useState<WorkspaceState>(emptyWorkspace), [draft, setDraft] = useState(defaultProject), [loading, setLoading] = useState(signedIn), [ready, setReady] = useState(false), [editTask, setEditTask] = useState<{id:string;text:string;due:string}|null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [legacy, setLegacy] = useState(false), [legacySummary, setLegacySummary] = useState(""), [replaceProject, setReplaceProject] = useState(false), [selection, setSelection] = useState<string[]>([]), [taskText, setTaskText] = useState(""), [taskDue, setTaskDue] = useState("");
  const draftDirty = useRef(false);
  useEffect(() => {
    const sync = () => { const record = workspaceSnapshot(); setState(record.state); if (!draftDirty.current) setDraft(record.state.project ? { ...defaultProject, ...record.state.project, stage: record.state.project.stage ?? "idea", goals: record.state.project.goals ?? [] } : defaultProject); };
    if (signedIn) void initializeWorkspace().then(() => { sync(); setReady(true); setLegacy(hasLegacyWorkspace()); setLoading(false); }).catch(() => { setMessage(en ? "Your workspace could not be loaded. Saved data is unchanged; refresh to retry." : "工作台暂时无法读取，已保存资料未改变，请刷新重试。"); setLoading(false); });
    window.addEventListener(ARCHIVE_EVENT, sync); return () => window.removeEventListener(ARCHIVE_EVENT, sync);
  }, [en, signedIn]);
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); setMessage(""); try { await action(); setReady(true); setMessage(success); return true; } catch (error) { setMessage(workspaceError(error, lang)); return false; } finally { setBusy(false); } }
  function changeProject<K extends keyof typeof defaultProject>(key: K, value: (typeof defaultProject)[K]) { draftDirty.current = true; setDraft(current => ({ ...current, [key]: value })); }
  async function submitProject(event: FormEvent) { event.preventDefault(); if (await run(() => saveProject(draft), en ? "Project saved." : "项目已保存。")) draftDirty.current = false; }
  async function addTask(event: FormEvent) { event.preventDefault(); if (await run(() => updateWorkspace(current => { current.tasks.unshift({ id: crypto.randomUUID(), text: taskText.trim(), due: taskDue, done: false, createdAt: new Date().toISOString() }); }), en ? "Action saved." : "行动已保存。")) { setTaskText(""); setTaskDue(""); } }
  function previewLegacy() { try { const data = readLegacyWorkspace(); setLegacySummary(en ? `${data.archive.length} evidence entries, ${data.decisions.length} decisions, ${data.completions.length} completed guides. Project: ${data.project?.name ?? "none"}.` : `${data.archive.length} 份证据、${data.decisions.length} 个判断、${data.completions.length} 篇完成记录。项目：${data.project?.name ?? "无"}。`); } catch { setMessage(en ? "The local archive could not be imported. Export it before making changes." : "本机档案无法直接迁入，请先导出保存。"); } }
  function exportLegacy() { const keys = ["pioneer:founder-archive-v1", "pioneer:guide-progress-v1", "pioneer:founder-project-v1", "pioneer:guide-decisions-v1"]; downloadWorkspace(Object.fromEntries(keys.map(key => [key, window.localStorage.getItem(key)])), "pioneer-legacy-backup.json"); }
  const project = state.project, stage = project?.stage ?? "idea", goals = project?.goals ?? [];
  const recommended = [...new Set([...guideByStage[stage], ...goals.flatMap(goal => guideByGoal[goal])])].filter(slug => !state.completions.includes(slug));
  const compare = selection.filter(slug => state.shortlist.includes(slug)).map(slug => catalog.find(row => row.slug === slug)).filter((row): row is WorkspaceResource => !!row);
  const guideNames = Object.fromEntries(guides.map(row => [row.slug, row.title]));
  if (!signedIn) return <section className="product-panel workspace-gate"><h1>{en ? "Your founder workspace" : "你的创业工作台"}</h1><p>{en ? "Save your project, evidence, decisions, actions and resource shortlist privately across devices." : "私密保存项目、证据、判断、行动与资源清单，在不同设备继续推进。"}</p><a className="product-button" href={`/signin-with-chatgpt?return_to=${encodeURIComponent(`${prefix}/workspace`)}`} target="_top">{en ? "Sign in with ChatGPT" : "使用 ChatGPT 登录"}</a><p><Link href={`${prefix}/knowledge`}>{en ? "Explore guides without signing in" : "先阅读创业指南"}</Link></p></section>;
  return <>
    <div className="product-heading"><div><h1>{en ? "Your founder workspace" : "你的创业工作台"}</h1><p>{en ? "Account" : "登录账号"}：{accountLabel}</p><p>{en ? "Turn your current risk into one verifiable next action." : "把当前最大的风险，变成一个可验证的下一步。"}</p></div><button type="button" className="product-button" disabled={busy || loading} onClick={() => run(refreshWorkspace, en ? "Latest workspace loaded; any project draft is retained." : "已读取最新档案，未保存的项目输入仍保留。")}>{en ? "Refresh" : "刷新档案"}</button></div>
    {message && <p role="status" className="workspace-message">{message}</p>}{loading && <p role="status">{en ? "Loading your private workspace…" : "正在读取私密工作台…"}</p>}
    <div className="workspace-summary"><article><span>{en ? "Current risk" : "当前风险"}</span><strong>{project?.currentRisk || (en ? "Define the assumption most likely to fail" : "先写下最可能失效的假设")}</strong></article><article><span>{en ? "Next action" : "下一步行动"}</span><strong>{project?.nextAction || (en ? "Collect evidence before adding features" : "先收集证据，再增加功能")}</strong></article><article><span>{en ? "Progress" : "行动进展"}</span><strong>{state.tasks.filter(task => task.done).length} / {state.tasks.length} {en ? "actions" : "个行动"}</strong><small>{state.completions.length} / {guides.length} {en ? "guides completed" : "篇指南完成"}</small></article></div>
    <div className="product-grid workspace-main-grid"><section className="product-panel"><h2>{en ? "Project and priorities" : "项目与优先事项"}</h2><form className="product-form" onSubmit={submitProject}>{([["name", en ? "Project name" : "项目名称", 120], ["oneLine", en ? "Who you help and what outcome you deliver" : "为谁，交付什么结果", 1200], ["targetUser", en ? "Specific target user" : "具体目标用户", 1200], ["currentRisk", en ? "Riskiest assumption" : "最危险的假设", 1200], ["nextAction", en ? "This week's next action" : "本周下一步", 1200]] as const).map(([key, label, max]) => <label className="wide" key={key}>{label}<textarea rows={key === "name" ? 1 : 2} value={draft[key]} maxLength={max} required={key === "name"} onChange={event => changeProject(key, event.target.value)} /></label>)}<label>{en ? "Stage" : "阶段"}<select value={draft.stage} onChange={event => changeProject("stage", event.target.value as FounderStage)}>{Object.entries(stages[lang]).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><fieldset className="wide"><legend>{en ? "Current priorities" : "当前目标"}</legend>{Object.entries(goalLabels[lang]).map(([goal, label]) => <label className="workspace-check" key={goal}><input type="checkbox" checked={draft.goals.includes(goal as FounderGoal)} onChange={event => changeProject("goals", event.target.checked ? [...draft.goals, goal as FounderGoal] : draft.goals.filter(value => value !== goal))} />{label}</label>)}</fieldset><button type="submit" disabled={busy || loading}>{en ? "Save project" : "保存项目"}</button></form></section>
      <section className="product-panel"><h2>{en ? "Suggested decisions" : "建议先做的判断"}</h2><p>{en ? `Based on your saved stage (${stages.en[stage]}) and selected priorities. These are starting points; choose the step that addresses your actual blocker.` : `根据已保存阶段（${stages.zh[stage]}）及目标选择；请优先完成能解决真实阻力的一步。`}</p><ul className="workspace-guide-list">{recommended.map(slug => <li key={slug}><Link href={`${prefix}/knowledge/${slug}`}>{guideNames[slug] ?? slug}</Link><button type="button" disabled={busy || loading} onClick={() => run(() => updateWorkspace(current => { current.tasks.unshift({ id: crypto.randomUUID(), text: guideNames[slug] ?? slug, due: "", done: false, createdAt: new Date().toISOString() }); }), en ? "Added to actions. Define your evidence and deadline." : "已加入行动，请补充证据标准与日期。")}>{en ? "Add action" : "加入行动"}</button></li>)}</ul>{recommended.length === 0 && <p>{en ? "All suggested guides are complete. Review your evidence and set the next experiment." : "建议指南已完成。回看证据，设置下一轮实验。"}</p>}<p><Link href={`${prefix}/weekly`}>{en ? "Check this week's verified opportunities" : "查看本周核验机会"}</Link> · <Link href={`${prefix}/programs`}>{en ? "Find relevant resources" : "寻找匹配资源"}</Link></p></section></div>
    <section className="product-panel"><h2>{en ? "Action list" : "行动清单"}</h2><form className="workspace-task-form" onSubmit={addTask}><label>{en ? "Action and evidence you will collect" : "行动与要收集的证据"}<input value={taskText} onChange={event => setTaskText(event.target.value)} required maxLength={500} placeholder={en ? "Interview 3 recent buyers; record actual alternatives" : "访谈 3 位近期购买者，记录实际替代行为"} /></label><label>{en ? "Target date (optional)" : "目标日期（可选）"}<input type="date" value={taskDue} onChange={event => setTaskDue(event.target.value)} /></label><button disabled={busy || loading} type="submit">{en ? "Add action" : "加入行动"}</button></form>{state.tasks.length === 0 && <p>{en ? "No actions yet. Choose one experiment with an observable result." : "还没有行动。先选一个能产生可观察结果的实验。"}</p>}<ul className="workspace-task-list">{state.tasks.map(task => <li key={task.id}>{editTask?.id === task.id ? <form className="workspace-task-form" onSubmit={async event => { event.preventDefault(); if (await run(() => updateWorkspace(current => { const row = current.tasks.find(value => value.id === task.id); if (row && editTask) { row.text = editTask.text.trim(); row.due = editTask.due; } }), en ? "Action updated." : "行动已更新。")) setEditTask(null); }}><label>{en ? "Edit action" : "编辑行动"}<input required maxLength={500} value={editTask.text} onChange={event => setEditTask(current => current ? {...current,text:event.target.value} : null)} /></label><label>{en ? "Target date" : "目标日期"}<input type="date" value={editTask.due} onChange={event => setEditTask(current => current ? {...current,due:event.target.value} : null)} /></label><button type="submit" disabled={busy}>{en ? "Save" : "保存"}</button><button type="button" disabled={busy} onClick={() => setEditTask(null)}>{en ? "Cancel" : "取消"}</button></form> : <><label><input type="checkbox" checked={task.done} disabled={busy || loading} onChange={() => run(() => updateWorkspace(current => { const row = current.tasks.find(value => value.id === task.id); if (row) row.done = !row.done; }), en ? "Action updated." : "行动已更新。")}/><span>{task.text}</span></label><button type="button" disabled={busy || loading} onClick={() => setEditTask({id:task.id,text:task.text,due:task.due})}>{en ? "Edit" : "编辑"}</button><small>{task.due || (en ? "No target date" : "未设日期")}</small><button type="button" disabled={busy || loading} onClick={() => run(() => updateWorkspace(current => { current.tasks = current.tasks.filter(value => value.id !== task.id); }), en ? "Action removed." : "行动已移除。")}>{en ? "Remove" : "移除"}</button></>}</li>)}</ul></section>
    <section className="product-panel"><h2>{en ? "Resource shortlist and comparison" : "资源清单与对比"}</h2><p>{en ? "Save resources from directories or briefs. Select up to four to compare fit, timing and tradeoffs. A review date is not a guarantee of current availability." : "在目录或详情中加入资源；选择最多 4 条，对比适合人群、时间与代价。核验日期不等于当前仍开放。"}</p>{state.shortlist.length === 0 && <p><Link href={`${prefix}/programs`}>{en ? "Start with startup programs" : "从开放计划开始寻找"}</Link></p>}<ul className="workspace-shortlist">{state.shortlist.map(slug => { const row = catalog.find(value => value.slug === slug); return <li key={slug}><label><input type="checkbox" checked={selection.includes(slug)} disabled={!row || (!selection.includes(slug) && selection.length >= 4)} onChange={event => setSelection(current => event.target.checked ? [...current, slug] : current.filter(value => value !== slug))} />{row ? <Link href={row.href}>{row.name}</Link> : <span>{slug} · {en ? "Unavailable or withdrawn" : "已不可用或撤回"}</span>}</label><button type="button" disabled={busy || loading} onClick={() => { setSelection(current => current.filter(value => value !== slug)); void run(() => updateWorkspace(current => { current.shortlist = current.shortlist.filter(value => value !== slug); }), en ? "Resource removed." : "资源已移除。"); }}>{en ? "Remove" : "移除"}</button></li>; })}</ul>{compare.length > 0 && <div className="workspace-table-scroll"><table className="workspace-compare"><caption>{en ? "Selected resource comparison" : "已选资源对比"}</caption><thead><tr><th scope="col">{en ? "Decision factor" : "判断因素"}</th>{compare.map(row => <th scope="col" key={row.slug}><Link href={row.href}>{row.name}</Link></th>)}</tr></thead><tbody>{([['location', en ? 'Location' : '地区'], ['timing', en ? 'Timing' : '时间'], ['status', en ? 'Recorded status' : '档案状态'], ['verified', en ? 'Review date' : '核验日期']] as const).map(([key, label]) => <tr key={key}><th scope="row">{label}</th>{compare.map(row => <td key={row.slug}>{row[key]}</td>)}</tr>)}<tr><th scope="row">{en ? "Best for" : "适合人群"}</th>{compare.map(row => <td key={row.slug}><ul>{row.fit.map(item => <li key={item}>{item}</li>)}</ul></td>)}</tr><tr><th scope="row">{en ? "Tradeoffs to check" : "需核对的代价"}</th>{compare.map(row => <td key={row.slug}><ul>{row.cautions.map(item => <li key={item}>{item}</li>)}</ul></td>)}</tr></tbody></table></div>}</section>
    <div className="product-grid"><section className="product-panel"><h2>{en ? "Evidence archive" : "证据档案"}</h2>{state.archive.length === 0 && <p>{en ? "Save a completed worksheet from a guide to bring its evidence here." : "在指南工作表中主动保存结果，证据会汇总到这里。"}</p>}{state.archive.map(entry => <details className="workspace-evidence" key={entry.id}><summary>{entry.title} · {entry.savedAt.slice(0, 10)}</summary><p>{entry.summary}</p><pre>{entry.content}</pre><p><Link href={`${prefix}/knowledge/${entry.guide}`}>{en ? "Open guide" : "查看指南"}</Link></p><button type="button" disabled={busy || loading} onClick={() => run(() => updateWorkspace(current => { current.archive = current.archive.filter(value => value.id !== entry.id); }), en ? "Evidence removed." : "证据已移除。")}>{en ? "Remove evidence" : "移除此份证据"}</button></details>)}</section><section className="product-panel"><h2>{en ? "Decisions and completion" : "判断与完成记录"}</h2>{state.decisions.length === 0 && <p>{en ? "Record your decision and supporting evidence after each guide." : "每篇指南结束后，记录方向判断及支持证据。"}</p>}{state.decisions.map(row => <article className="workspace-decision" key={row.guide}><h3><Link href={`${prefix}/knowledge/${row.guide}`}>{guideNames[row.guide] ?? row.guide}</Link></h3><strong>{({ continue: en ? "Continue" : "继续", narrow: en ? "Narrow" : "缩小", change: en ? "Change" : "调整", stop: en ? "Stop" : "停止" })[row.decision]}</strong><p>{row.reason}</p><small>{row.savedAt.slice(0, 10)}</small></article>)}<h3>{en ? "Completed guides" : "已完成指南"}</h3><ul>{state.completions.map(slug => <li key={slug}><Link href={`${prefix}/knowledge/${slug}`}>{guideNames[slug] ?? slug}</Link></li>)}</ul></section></div>
    <section className="product-panel"><h2>{en ? "Your data" : "你的资料"}</h2><p>{en ? "Export a copy before clearing. Clearing removes account-synced project content, actions, evidence, decisions and saved resources across your devices; a version marker prevents stale tabs from restoring it." : "清空前可导出副本。清空会移除账号内同步到所有设备的项目内容、行动、证据、判断及收藏；系统仅保留版本标记，防止旧页面恢复已清空内容。"}</p><div className="workspace-data-actions"><button type="button" disabled={busy || loading || !ready} onClick={() => downloadWorkspace({ exportedAt: new Date().toISOString(), ...workspaceSnapshot() })}>{en ? "Export my workspace" : "导出我的工作台"}</button><button type="button" disabled={busy || loading || !ready} onClick={() => { if (window.confirm(en ? "Clear all your saved founder data across devices? Export a copy first if needed." : "清空所有设备上的创业资料？如需保留，请先导出副本。")) void run(async () => { await clearWorkspaceData(); draftDirty.current = false; setDraft(defaultProject); setSelection([]); }, en ? "Workspace cleared." : "工作台已清空。"); }}>{en ? "Clear my data" : "清空我的资料"}</button><a href={`/signout-with-chatgpt?return_to=${encodeURIComponent(`${prefix}/workspace`)}`} target="_top">{en ? "Sign out" : "退出登录"}</a></div>{legacy && <div className="workspace-migration"><h3>{en ? "Existing local archive" : "已有本机档案"}</h3><p>{en ? "Your old browser archive has not been uploaded. Inspect it, then choose whether to merge it into this signed-in account. Local originals are retained." : "旧浏览器档案尚未上传。先查看内容，再选择是否迁入当前登录账号；本机原件会保留。"}</p><button type="button" onClick={previewLegacy}>{en ? "Inspect local archive" : "查看本机档案"}</button><button type="button" onClick={() => { if (window.confirm(en ? "Remove this device's old browser archive? This will not clear your signed-in workspace." : "删除本设备的旧浏览器档案？此操作不会清空登录账号的工作台。")) { ["pioneer:founder-archive-v1", "pioneer:guide-progress-v1", "pioneer:founder-project-v1", "pioneer:guide-decisions-v1"].forEach(key => window.localStorage.removeItem(key)); setLegacy(false); setLegacySummary(""); } }}>{en ? "Delete local originals" : "删除本机原件"}</button><button type="button" onClick={exportLegacy}>{en ? "Export local backup" : "导出本机备份"}</button>{legacySummary && <><p>{legacySummary}</p><label className="workspace-check"><input type="checkbox" checked={replaceProject} onChange={event => setReplaceProject(event.target.checked)} />{en ? "Replace my cloud project with the local project" : "用本机项目替换云端项目"}</label><button type="button" disabled={busy || loading} onClick={() => run(() => importLegacyWorkspace(replaceProject), en ? "Local archive merged. The local original remains on this device." : "本机档案已迁入，原件仍保留在本设备。")}>{en ? "Merge into this account" : "确认迁入当前账号"}</button></>}</div>}</section>
  </>;
}
