"use client";
import {useEffect,useState} from 'react';
import {SiteHeader,SiteFooter} from './SiteChrome';
import {SaveResource} from './SaveResource';
import {HomeIcon} from './HomeVisuals';
import {resources,type Resource} from '../data/resources';
import {getEnglishResource} from '../data/english';
import {freshnessLabel,resourceFreshness} from '../lib/resourceFreshness';
import {weeklyIssue,weeklyOpportunities,isWeeklyCurrent} from '../data/weekly';
import {resourceCardSummary} from '../lib/resourceCardSummary';
import {CardFactIcon} from './CardFactIcon';
import {matchesGlobePlace} from '../lib/globeDiscovery';
import {geoMercator,geoPath} from 'd3-geo';
import world from '../data/globeCountries.json';

type Lang='zh'|'en';
export function OutlineIcon({kind}:{kind:string}){
 const paths:Record<string,React.ReactNode>={bookmark:<path d="M7 3h10v18l-5-4-5 4z"/>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></>,target:<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/></>,rocket:<><path d="M8 16 5 13c1-6 7-10 15-10 0 8-4 14-10 15z"/><circle cx="15" cy="8" r="2"/><path d="m5 16-2 5 5-2M4 12l-1-6 7 1M12 20l6 1-1-7"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2v6M17 2v6M3 11h18M7 15h4"/></>,bulb:<><path d="M8 16a7 7 0 1 1 8 0v4H8zM9 23h6"/></>,book:<><path d="M12 5c-4-3-8-3-10-1v17c3-2 7-2 10 0 3-2 7-2 10 0V4c-2-2-6-2-10 1zM12 5v16"/></>,building:<><path d="m2 8 10-6 10 6M4 9h16M6 9v12M12 9v12M18 9v12M2 22h20"/></>,mail:<><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m2 5 10 8L22 5"/></>};
 return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[kind]??paths.target}</svg>;
}
export function HomeHeader({lang}:{lang:Lang}){return <SiteHeader lang={lang}/>;}
export function WeeklyCards({lang}:{lang:Lang}){
 const en=lang==='en',prefix=en?'/en':'',[current,setCurrent]=useState(false),[now,setNow]=useState(0);
 useEffect(()=>{const update=()=>{setCurrent(isWeeklyCurrent());setNow(Date.now());};update();const timer=setInterval(update,60000);return()=>clearInterval(timer);},[]);
 const slugs=['y-combinator','techstars-accelerators','slush-2026','slush-2026'];
 return <section className="design-weekly design-width"><div className="design-section-heading"><div><h2>{current?(en?'Worth acting on this week':'本周值得行动'):(en?'Latest checked founder brief':'最近一期 · 4 个创业机会核验')}</h2><span className="weekly-label">WEEKLY SIGNAL <b>{weeklyIssue.id}</b></span><p>{en?'Verified applications, introductions and upcoming events.':'从已核验资源中筛选出的开放申请、对接与近期活动。'}</p></div><div className="weekly-heading-right"><span>{weeklyIssue.range}</span><a href={`${prefix}/weekly`}>{en?'View all':'查看全部'} →</a></div></div><div className="design-weekly-grid">{weeklyOpportunities.map((row,i)=>{const r=resources.find(r=>r.slug===slugs[i]);const stale=!current||now>=Date.parse(row.expiresAt);return <article className="weekly-opportunity" key={row.id}><div className="weekly-card-brand"><span className={`weekly-logo weekly-logo-${i}`}>{['Y','T','SLUSH','SLUSH'][i]}</span><strong>{['Y Combinator','Techstars','Slush 365','Slush'][i]}</strong><span className={`weekly-state ${stale?'needs-review':i<2?'open':'upcoming'}`}><i/>{stale?(en?'RECHECK':'待核验'):i<2?'OPEN':'UPCOMING'}</span></div><h3><a className="card-cover-link" href={`${prefix}/weekly`}>{row.name}</a></h3><p>{row[lang].description}</p><div className="weekly-facts"><span><HomeIcon kind="compass"/>{row.location}</span><span><CardFactIcon kind="calendar"/>{row[lang].deadline}</span></div><div className="design-tags"><span>{row.kind==='event'?'Event':'Early stage'}</span><span>{i<2?'Tech':'Investors'}</span><span>{i<2?'Global':'Europe'}</span></div><div className="weekly-card-bottom"><small>{en?'Checked':'核验'} {weeklyIssue.checkedAt}</small>{r&&<SaveResource slug={r.slug} lang={lang}/>}<span aria-hidden="true">→</span></div></article>;})}</div></section>;
}
export function NeedGrid({lang}:{lang:Lang}){
 const en=lang==='en',p=en?'/en':'';
 const rows=[['target','找资金','Funding','VC · Grants','organizations?need=funding','funding'],['rocket','找加速器','Accelerators','Accelerators','programs?need=funding','program'],['globe','出海 / 落地','Market entry','Market Entry','organizations?need=support','organization'],['calendar','参加活动','Attend events','Events','events','event'],['people','找创业社区','Communities','Communities','community','community'],['bulb','寻找项目','Startup projects','Startup Projects','startups','startup'],['book','学习创业','Learn to build','Knowledge','knowledge','knowledge'],['building','找机构','Organizations','Organizations','organizations','organization']];
 return <section className="design-needs design-width" id="categories"><div className="design-section-heading"><div><h2>{en?'What are you trying to solve?':'你现在想解决什么？'}</h2><p>{en?'Find resources that match your next step.':'按你的目标发现最相关的资源。'}</p></div><a href={`${p}/knowledge/find-the-real-problem`}>{en?'Not sure? Start here':'不确定从哪里开始？试试我们的推荐'} →</a></div><div className="design-needs-grid">{rows.map(([icon,zh,title,note,path,type])=><a className="design-need" key={zh} href={`${p}/${path}`} data-audience-event="directory:open" data-audience-target={zh}>{['globe','people'].includes(icon)?<HomeIcon kind={icon as 'globe'|'people'}/>:<OutlineIcon kind={icon}/>}<strong>{en?title:zh}</strong><span>{note}</span><small>{type==='knowledge'?(en?'Founder guides':'创业指南'):type==='community'?(en?'Community picks':'社区推荐'):`${resources.filter(r=>type==='funding'?/投资|VC|venture capital/i.test(r.kind):r.type===type).length} ${en?'resources':'条资源'}`} <b>→</b></small></a>)}</div></section>;
}
export function resourceImage(resource:Resource){
 if(resource.slug==='web-summit-lisbon-2026')return '/home/web-summit.jpg';
 if(resource.type==='event')return '/events/disrupt-audience.webp';
 if(resource.slug==='nvidia-inception')return '/home/singapore.jpg';
 if(/新加坡|Singapore/.test(resource.location))return '/home/singapore.jpg';
 if(resource.type==='startup')return resource.slug==='xiaoyu-robotics'?'/startups/xiaoyu-robotics/product-hero.webp':'/home/earth-surface.jpg';
 return '/home/san-francisco.jpg';
}
export function PhotoResourceCard({resource,lang}:{resource:Resource;lang:Lang}){
 const en=lang==='en',copy=(en?getEnglishResource(resource.slug):undefined)??resource,p=en?'/en':'',fresh=resourceFreshness(resource),facts=resourceCardSummary(resource,lang);
 return <article className="design-photo-card"><div className="resource-photo"><img src={resourceImage(resource)} alt={en?'Location or topic illustration':'所在地或主题配图'} loading="lazy"/>{resource.featured&&<span className="featured-badge">FEATURED</span>}<SaveResource slug={resource.slug} lang={lang}/></div><div className="photo-card-body"><h3><a className="card-cover-link" href={resource.detailPath?`${p}${resource.detailPath}`:`${p}/resources/${resource.slug}`}>{resource.name}</a></h3><p>{copy.description}</p><div className="design-tags">{copy.tags.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div><small className="photo-freshness">{freshnessLabel(fresh,lang)} · {resource.verified.match(/\d{4}.\d{2}.\d{2}/)?.[0]}</small><div className="photo-facts" aria-label={en?'Decision facts':'决策信息'}>{facts.map(f=><span key={f.label}>{f.label}: {f.value}</span>)}</div></div></article>;
}
const ecosystems=[{id:'country:SGP',name:'Singapore',zh:'新加坡',lon:103.82,lat:1.35},{id:'city:USA:San Francisco',name:'San Francisco',zh:'旧金山',lon:-122.42,lat:37.77},{id:'city:GBR:London',name:'London',zh:'伦敦',lon:-.12,lat:51.5},{id:'city:USA:New York',name:'New York',zh:'纽约',lon:-74,lat:40.71},{id:'city:JPN:Tokyo',name:'Tokyo',zh:'东京',lon:139.69,lat:35.68}];
export function EcosystemSection({lang,onSelect}:{lang:Lang;onSelect:(id:string)=>void}){
 const en=lang==='en',[selected,setSelected]=useState(ecosystems[0]),projection=geoMercator().scale(68).translate([260,140]),path=geoPath(projection),catalog=resources.filter(r=>matchesGlobePlace(r,selected.id));
 return <section className="design-ecosystems design-width"><div className="ecosystem-list"><h2>{en?'Explore startup ecosystems':'探索全球创业生态'}</h2><p>{en?'Discover local opportunities, ideas and resources.':'发现不同城市和地区的创业机会、趋势与资源。'}</p>{ecosystems.map((city,i)=>{const rows=resources.filter(r=>matchesGlobePlace(r,city.id));return <button key={city.id} onClick={()=>setSelected(city)} aria-pressed={selected.id===city.id}><small>0{i+1}</small><strong>{city.name}</strong><span>{rows.length} {en?'resources':'条资源'}</span><b>→</b></button>;})}</div><svg className="ecosystem-map" viewBox="0 0 520 285" role="img" aria-label={en?'Startup ecosystem locations':'创业生态地点'}><defs><pattern id="ecosystem-dots" width="3" height="3" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#bcc2c2"/></pattern></defs>{world.features.filter(f=>!('maritime'in f.properties&&f.properties.maritime)).map((f,i)=><path key={i} d={path(f as never)??''} fill="url(#ecosystem-dots)"/>)}{ecosystems.map(city=>{const xy=projection([city.lon,city.lat])!;return <g key={city.id} transform={`translate(${xy[0]},${xy[1]})`} onClick={()=>setSelected(city)} className="ecosystem-dot"><circle r="10" fill="#ff5c2620" stroke="#ff6b3838"/><circle r="5" fill="#ff5b2a" stroke="#fff" strokeWidth="2"/><text x={city.lon<-50?-13:13} y={city.name==='London'?-12:5} textAnchor={city.lon<-50?'end':'start'}>{city.name}</text></g>;})}</svg><article className="ecosystem-feature"><div><img src={selected.id==='country:SGP'?'/home/singapore.jpg':'/home/san-francisco.jpg'} alt={selected.id==='country:SGP'?'Singapore waterfront':'San Francisco waterfront illustration'}/><span>EXPLORE</span></div><h3>{selected.name}</h3><p>{en?'Find your next connection and opportunity.':'连接创业网络，发现下一站机会。'}</p><div className="ecosystem-counts"><span><b>{catalog.length}</b>{en?'Resources':'资源总数'}</span><span><b>{catalog.filter(r=>r.type==='program').length}</b>{en?'Programs':'创业计划'}</span><span><b>{catalog.filter(r=>r.type==='event').length}</b>{en?'Events':'活动档案'}</span></div><button onClick={()=>onSelect(selected.id)}>{en?`Explore ${selected.name}`:`探索${selected.zh}`} →</button></article></section>;
}
export function GuideStrip({lang}:{lang:Lang}){const en=lang==='en',p=en?'/en':'';return <section className="design-guide-strip"><div className="design-width"><div className="guide-strip-art" aria-hidden="true"/><div className="guide-strip-title"><span>FOUNDER GUIDE</span><h2>{en?'From idea to impact':'从想法到影响力'}</h2><p>{en?'A practical guide for every next step.':'实用的创业指南，陪伴你走好每一步。'}</p></div><div className="guide-strip-links">{[['find-the-real-problem','问题验证','Problem'],['first-user-interview','用户访谈','Interview'],['define-your-mvp','MVP','MVP'],['decide-whether-to-fundraise','融资','Funding']].map(([slug,zh,title],i)=><a key={slug} href={`${p}/knowledge/${slug}`}><small>0{i+1}</small><strong>{en?title:zh}</strong><span>{en?'Read the guide':'阅读完整指南'} →</span></a>)}</div></div></section>;}
export function HomeFooter({lang}:{lang:Lang}){return <SiteFooter lang={lang}/>;}
