"use client";
import {useEffect,useRef,useState} from 'react';
import {geoMercator,geoPath} from 'd3-geo';
import world from '../data/globeCountries.json';
import type {Resource,ResourceType} from '../data/resources';
import {globePlaces,globeCities,chinaRegions,matchesGlobePlace} from '../lib/globeDiscovery';
import {getEnglishResource} from '../data/english';
import {freshnessLabel,resourceFreshness} from '../lib/resourceFreshness';
import {SaveResource} from './SaveResource';
type Tab='overview'|'resources'|'event'|'organization'|'guide';
export function LocationPanel({id,lang,entries,onClose,onSelect,onView,loading,error}:{id:string;lang:'zh'|'en';entries:Resource[];onClose:()=>void;onSelect:(id:string)=>void;onView:(type?:ResourceType)=>void;loading:boolean;error:boolean}){
 const en=lang==='en',prefix=en?'/en':'',place=globePlaces.find(p=>p.id===id)!,country=place.parent?globePlaces.find(p=>p.id===place.parent)!:place;
 const dialog=useRef<HTMLDialogElement>(null),[tab,setTab]=useState<Tab>('overview');
 const [tabLocation,setTabLocation]=useState(id);
 // Reset the tab before rendering a different place, without remounting the dialog.
 if(tabLocation!==id){setTabLocation(id);setTab('overview');}
 const rows=entries.filter(r=>matchesGlobePlace(r,id));
 const cities=globeCities.filter(p=>p.parent===country.id),regions=country.id==='country:CHN'?chinaRegions:[];
 const eventCount=rows.filter(r=>r.type==='event').length,orgCount=rows.filter(r=>r.type==='organization').length;
 const shown=(tab==='event'||tab==='organization'?rows.filter(r=>r.type===tab):rows).slice(0,tab==='overview'?3:20);
 useEffect(()=>{const previouslyFocused=document.activeElement as HTMLElement|null;dialog.current?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;previouslyFocused?.focus();};},[]);
 useEffect(()=>{dialog.current?.scrollTo({top:0});},[id]);
 const features=world.features.filter(f=>f.properties.id===country.id);
 const projection=geoMercator();if(features.length)projection.fitExtent([[30,15],[410,155]],{type:'FeatureCollection',features} as never);
 const path=geoPath(projection),point=projection([place.lon,place.lat]);
 const photo=country.id==='country:SGP'?'/home/singapore.jpg':country.id==='country:USA'&&(id===country.id||place.en==='San Francisco')?'/home/san-francisco.jpg':undefined;
 return <dialog ref={dialog} className="location-panel" aria-labelledby="location-panel-title" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const box=e.currentTarget.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)onClose();}}}>
 <header className="location-panel-header"><span className="location-emblem" aria-hidden="true">{country.id==='country:CHN'?'🇨🇳':country.id==='country:USA'?'🇺🇸':country.id==='country:SGP'?'🇸🇬':'◎'}</span><div><nav aria-label={en?'Selected location':'所选地点'}><button onClick={()=>onSelect(country.id)}>{country[lang]}</button>{place.parent&&<> / {place[lang]}</>}</nav><h2 id="location-panel-title">{place[lang]}</h2><span>{place[en?'zh':'en']} · {en?'Founder ecosystem':'创业生态'}</span></div><button className="location-close" onClick={onClose} aria-label={en?'Close location panel':'关闭地点面板'}>×</button></header>
 <div className="location-tabs" role="tablist" aria-label={en?'Location details':'地点详情'}>{([['overview',en?'Overview':'概览'],['resources',`${en?'Resources':'资源'} ${rows.length}`],['event',`${en?'Events':'活动'} ${eventCount}`],['organization',`${en?'Institutions':'机构'} ${orgCount}`],['guide',en?'Guide':'指南']] as [Tab,string][]).map(([key,label])=><button key={key} role="tab" id={`location-tab-${key}`} aria-controls="location-tab-content" aria-selected={tab===key} onClick={()=>setTab(key)} onKeyDown={e=>{const keys:Tab[]=['overview','resources','event','organization','guide'];if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=keys[(keys.indexOf(key)+(e.key==='ArrowRight'?1:4))%5];setTab(next);document.getElementById(`location-tab-${next}`)?.focus();}}} tabIndex={tab===key?0:-1}>{label}</button>)}</div>
 <div id="location-tab-content" role="tabpanel" aria-labelledby={`location-tab-${tab}`}>
 {tab==='overview'&&<><div className={`location-banner ${photo?'has-photo':''}`}>{photo?<img src={photo} alt={country.id==='country:SGP'?'Singapore waterfront':'San Francisco waterfront'}/>:<svg viewBox="0 0 440 170" aria-hidden="true">{features.map((f,i)=><path key={i} d={path(f as never)??''}/>)}{place.parent&&point&&<circle cx={point[0]} cy={point[1]} r="4"/>}</svg>}<span>{en?'Find your next connection.':'发现下一站机会。'}</span></div><p className="location-intro">{en?`Explore programs, institutions, events and startup projects in ${place.en}. Open a resource to check its audience, dates and official sources.`:`探索${place.zh}的创业计划、机构、活动与项目。进入资源详情，可查看适合人群、时间和官方来源。`}</p><div className="location-stats"><span><b>{rows.length}</b>{en?'Resources':'资源总数'}</span><span><b>{rows.filter(r=>r.type==='program').length}</b>{en?'Programs':'创业计划'}</span><span><b>{eventCount}</b>{en?'Events':'活动档案'}</span><span><b>{orgCount}</b>{en?'Institutions':'机构'}</span></div></>}
 {(tab==='overview'||tab==='resources')&&cities.length>0&&<div className="location-subplaces"><h3>{en?'Explore cities':'探索城市'}</h3><div>{cities.map(p=><button key={p.id} aria-pressed={id===p.id} onClick={()=>onSelect(p.id)}>{p[lang]} <small>{entries.filter(r=>matchesGlobePlace(r,p.id)).length}</small></button>)}</div>{regions.length>0&&<details><summary>{en?'All 34 provincial-level areas':'全部 34 个省级地区'}</summary><div>{regions.map(p=><button key={p.id} aria-pressed={id===p.id} onClick={()=>onSelect(p.id)}>{p[lang]} <small>{entries.filter(r=>matchesGlobePlace(r,p.id)).length}</small></button>)}</div></details>}</div>}
 {loading&&<p className="location-data-note" role="status">{en?'Loading community resources…':'正在加载社区资源…'}</p>}{error&&<p className="location-data-note">{en?'Community resources are temporarily unavailable; showing curated archives.':'社区资源暂时无法加载，当前展示站内整理档案。'}</p>}
 {tab==='guide'?<div className="location-guides"><h3>{en?'Prepare your next step':'为下一步做好准备'}</h3>{[['find-the-real-problem','问题验证','Validate the problem'],['first-user-interview','用户访谈','Interview users'],['define-your-mvp','定义 MVP','Define your MVP'],['decide-whether-to-fundraise','融资决策','Decide whether to fundraise']].map(([slug,zh,title])=><a key={slug} href={`${prefix}/knowledge/${slug}`}>{en?title:zh}<span>→</span></a>)}</div>:<section className="location-resource-list"><div className="location-list-heading"><h3>{tab==='overview'?(en?'Explore these resources':'值得探索的资源'):tab==='event'?(en?'Event archives':'活动档案'):tab==='organization'?(en?'Institutions':'创业机构'):(en?'Resources':'资源清单')}</h3><button onClick={()=>onView(tab==='event'||tab==='organization'?tab:undefined)}>{en?'View all':'查看全部'} →</button></div>{shown.map(r=><article key={r.slug}><a href={`${prefix}/resources/${r.slug}`}><strong>{r.name}</strong><span>{en?getEnglishResource(r.slug)?.location??r.location:r.location}</span><small>{freshnessLabel(resourceFreshness(r),lang)}</small></a><SaveResource slug={r.slug} lang={lang}/><a className="location-resource-arrow" href={`${prefix}/resources/${r.slug}`} aria-label={`${en?'View':'查看'} ${r.name}`}>→</a></article>)}{!shown.length&&<div className="location-empty"><strong>{en?'No resources here yet':'这里暂未收录资源'}</strong><p>{en?'Try another city or contribute a resource.':'可以切换其他城市，或推荐你了解的创业资源。'}</p><a href={`${prefix}/submit`}>{en?'Contribute a resource':'推荐资源'} →</a></div>}</section>}
 <p className="location-data-note">{en?'Counts include historical archives and reflect resource locations, not application eligibility.':'数量含历史档案，按资源所在地统计，不代表申请资格。'}</p>
 </div><div className="location-panel-bottom"><button onClick={()=>onView(tab==='event'||tab==='organization'?tab:undefined)}>{en?`View ${place.en} resources`:`查看${place.zh}全部资源`} →</button></div>
 </dialog>;
}
