"use client";
import { useEffect, useState } from "react";
type Edition = { id: string; title: string; validUntil: string | null; zh: { subject: string; text: string }; en: { subject: string; text: string } };
type Status = { id: string; counts: { status: string; n: number }[]; deliveries: { id: string; status: string; attempts: number; error: string | null; provider_id: string | null; checked_at: string | null; next_attempt_at: number }[] };
type Dashboard = { enabled: boolean; sender: string | null; missing: string[]; guides: { slug: string; title: string }[]; campaigns: { id: string; topic: string; valid_until: string | null; created_at: string }[] };
const labels: Record<string, string> = { queued: "待发送", sending: "发送处理中", retry: "待重试", accepted: "服务商已接收，投递未确认", delivered: "服务商确认投递", undeliverable: "无法投递", failed: "发送失败", cancelled: "已取消", uncertain: "结果不确定，需人工核对" };
export function MailDashboard() {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null), [topic, setTopic] = useState("weekly"), [guide, setGuide] = useState("find-the-real-problem"), [preview, setPreview] = useState<{ edition: Edition; recipients: { language: string; n: number }[]; existing: boolean } | null>(null), [status, setStatus] = useState<Status | null>(null);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { const controller = new AbortController(); fetch("/api/admin/mail", { cache: "no-store", signal: controller.signal }).then(async response => { if (!response.ok) throw new Error(); setDashboard(await response.json()); }).catch(() => { if (!controller.signal.aborted) setMessage("发信后台无法读取，请确认管理员权限后重试。"); }); return () => controller.abort(); }, []);
  async function operate(action: string, id?: string) {
    setBusy(true); setMessage("");
    try {
      const response = await fetch("/api/admin/mail", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, id, topic, guide, confirmed: action === "enqueue" || action === "send" || action === "retry", editionId: preview?.edition.id }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "操作未完成");
      if (action === "preview") { setPreview(result); setStatus(null); }
      else if (action === "enqueue") { setMessage(`本次新增 ${result.added} 封待发送邮件；加入队列不代表已发出。`); const state = await fetch("/api/admin/mail", { cache: "no-store" }); if (state.ok) setDashboard(await state.json()); const detail = await fetch("/api/admin/mail", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "status", id: result.id }) }); if (detail.ok) setStatus(await detail.json()); }
      else { setStatus(result); if (action === "retry") setMessage(`重新加入 ${result.requeued} 封明确失败的邮件；尚未发送。不确定的结果保持暂停。`); if (action === "send") setMessage("本批已处理。请根据下方状态查看服务商接收、失败或等待重试的结果。"); }
    } catch (error) { setMessage(error instanceof Error ? error.message : "操作未完成，请保留选择并重试。"); }
    finally { setBusy(false); }
  }
  async function refresh() { setBusy(true); try { const r = await fetch("/api/admin/mail", { cache: "no-store" }); if (!r.ok) throw new Error(); setDashboard(await r.json()); setMessage(""); } catch { setMessage("后台读取失败，请稍后重试。"); } finally { setBusy(false); } }
  return <><div className="product-heading"><div><h1>通知发布与投递</h1><p>先核对内容和接收范围，再加入队列并明确发送。只有登录确认过对应主题、当前仍开启的账号会进入队列。</p></div><button className="product-button" type="button" disabled={busy} onClick={() => void refresh()}>刷新后台</button></div>
    {!dashboard ? <p role="status">{message || "正在读取发信状态…"}</p> : <>
      <section className="product-panel"><h2>{dashboard.enabled ? "发信通道已启用" : "发信通道尚未启用"}</h2><p>{dashboard.enabled ? "当前接入 Resend。服务商接收请求后，仍需检查投递状态；不要把接受请求当作送达。" : "可以预览邮件，加入队列和发送均暂停。需要可用的发信服务、已验证发信邮箱和明确启用配置。"}</p>{!dashboard.enabled && <p><a href="https://github.com/ZYX121212/pioneer/blob/main/docs/email-delivery.md" target="_blank" rel="noreferrer">发信配置说明</a></p>}<p>{dashboard.sender && `发信邮箱：${dashboard.sender}`}</p><p><a href="/admin/reviews">资源审核</a> · <a href="/admin/analytics">内部统计</a></p></section>
      <section className="product-panel"><h2>1 · 预览已发布内容</h2><div className="product-form"><label>通知主题<select disabled={busy} value={topic} onChange={e => { setTopic(e.target.value); setPreview(null); setStatus(null); }}><option value="weekly">本周机会</option><option value="cases">创业学习 / 指南</option></select></label>{topic === "cases" && <label>创业指南<select disabled={busy} value={guide} onChange={e => { setGuide(e.target.value); setPreview(null); setStatus(null); }}>{dashboard.guides.map(row => <option key={row.slug} value={row.slug}>{row.title}</option>)}</select></label>}<button type="button" disabled={busy} onClick={() => void operate("preview")}>预览中英文与接收范围</button></div>
      {preview && <div><h3>{preview.edition.title}</h3><p>当前确认主题的接收范围：{preview.recipients.length ? preview.recipients.map(row => `${row.language === "en" ? "英文" : "中文"} ${row.n} 位`).join(" · ") : "0 位"}。这是实时人数，发送前会再次检查退出和偏好。</p><p>同一期每个账号只加入一次；已有队列使用首次保存的内容。{preview.existing ? "此期已创建，下面展示保存版本。" : "本期尚未创建。"}</p>{preview.edition.validUntil && <p>核验有效期截止：{preview.edition.validUntil}</p>}{(["zh", "en"] as const).map(lang => <details key={lang}><summary>{lang === "zh" ? "中文邮件" : "English email"} · {preview.edition[lang].subject}</summary><pre className="mail-preview">{preview.edition[lang].text}</pre><p>实际邮件会附带个人退出链接与偏好管理入口；不会附带其他接收人的邮箱。</p></details>)}<button className="product-button" type="button" disabled={busy || !dashboard.enabled} onClick={() => { if (window.confirm("确认将下一批已确认主题且当前仍开启的账号加入发送队列？每批最多 20 封，此操作尚不发送。")) void operate("enqueue"); }}>2 · 确认加入下一批（最多 20 封）</button></div>}
      </section>
      <section className="product-panel"><h2>3 · 查看队列并发送</h2>{dashboard.campaigns.length === 0 && <p>尚无通知队列。预览后确认接收范围即可创建。</p>}<div className="mail-campaign-list">{dashboard.campaigns.map(row => <button className="product-button" type="button" key={row.id} disabled={busy} onClick={() => void operate("status", row.id)}>{row.id} · {row.created_at}</button>)}</div>{status && <div><h3>{status.id}</h3><p>{status.counts.length ? status.counts.map(row => `${labels[row.status] ?? row.status} ${row.n}`).join(" · ") : "当前队列为空"}</p><button className="product-button" type="button" disabled={busy || !dashboard.enabled} onClick={() => { if (window.confirm("确认发送下一批？每批最多 3 封，将向仍开启此主题的账号发送本期保存内容。")) void operate("send", status.id); }}>发送下一批（最多 3 封）</button><button className="product-button" type="button" disabled={busy || !dashboard.enabled} onClick={() => void operate("inspect", status.id)}>核对服务商投递状态</button><button className="product-button" type="button" disabled={busy} onClick={() => void operate("status", status.id)}>刷新队列状态</button><button className="product-button" type="button" disabled={busy || !dashboard.enabled} onClick={() => { if (window.confirm("已修复发信配置？此操作只重新加入服务商明确拒绝的邮件，不处理不确定结果，也不立即发送。")) void operate("retry", status.id); }}>配置修复后，重试明确失败</button><p>待重试邮件遵守服务商等待时间；结果不确定超过安全重试窗口后停止重发，需要核对服务商记录。已经接收的邮件只检查投递，不再次发送。</p><ul className="mail-delivery-list">{status.deliveries.map(row => <li key={row.id}><strong>{row.id}</strong> · {labels[row.status] ?? row.status} · 尝试 {row.attempts} 次{row.error && <span> · {row.error}</span>}{row.status === "retry" && <span> · 可重试于 {new Date(row.next_attempt_at).toISOString()}</span>}</li>)}</ul></div>}</section>
      <p aria-live="polite">{message}</p><p>{busy ? "正在处理，请等待结果…" : "预览与状态查询不会发送邮件。"}</p>
    </>}
  </>;
}
