"use client";
/* eslint-disable @next/next/no-img-element -- Local precompressed hero asset; its container reserves layout space. */
import Link from "next/link";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { Resource } from "../data/resources";
import { getEnglishResource } from "../data/english";
import { finderRegions, findResources } from "../lib/resourceFinder";
import { programDeadline, programFormat, programFunding, programHighlight, programStatus, type ProgramStatus } from "../lib/programDiscovery";
import { CardFactIcon } from "./CardFactIcon";
import { SaveResource } from "./SaveResource";
import { ProgramLogo } from "./ProgramLogo";
const initial = { q: "", status: "all", stage: "all", region: "all", kind: "all", funding: "all", format: "all", sort: "updated", need: "all", freshness: "all", page: "1" };
type Filters = typeof initial;
const statusCopy: Record<ProgramStatus, [string, string]> = { open: ["正在申请", "Open"], closing: ["即将截止", "Closing soon"], rolling: ["持续开放", "Rolling"], review: ["当前窗口待核验", "Window needs checking"], archived: ["历史批次", "Archived edition"], info: ["计划信息", "Program information"] };
function SearchIcon() { return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg>; }
export function ProgramsExperience({ resources, lang, unavailable }: { resources: Resource[]; lang: "zh" | "en"; unavailable: boolean }) {
  const en = lang === "en", t = (zh: string, english: string) => en ? english : zh, base = en ? "/en" : "";
  const [filters, setFilters] = useState<Filters>(initial), [now, setNow] = useState(() => new Date());
  useEffect(() => { const read = () => { const params = new URLSearchParams(window.location.search); setFilters(Object.fromEntries(Object.entries(initial).map(([key, value]) => [key, params.get(key) ?? value])) as Filters); }; read(); window.addEventListener("popstate", read); const timer = window.setInterval(() => setNow(new Date()), 60000); return () => { window.removeEventListener("popstate", read); window.clearInterval(timer); }; }, []);
  function update(values: Partial<Filters>, reset = true) { const next = { ...filters, ...(reset ? { page: "1" } : {}), ...values }; setFilters(next); const url = new URL(window.location.href); for (const [key, value] of Object.entries(next)) { if (value === initial[key as keyof Filters]) url.searchParams.delete(key); else url.searchParams.set(key, value); } window.history.replaceState(null, "", url); }
  const candidates = useMemo(() => findResources(resources, { query: filters.q, need: filters.need, region: filters.region, stage: filters.stage, freshness: filters.freshness }, lang, now).filter(r => (filters.kind === "all" || r.kind === filters.kind) && (filters.funding === "all" || programFunding(r) === filters.funding) && (filters.format === "all" || programFormat(r) === filters.format)), [resources, filters, lang, now]);
  const matchesStatus = (r: Resource, id: string) => id === "all" || (id === "open" ? ["open", "closing", "rolling"].includes(programStatus(r, now)) : programStatus(r, now) === id);
  const visible = candidates.filter(r => matchesStatus(r, filters.status)).sort((a, b) => filters.sort === "name" ? a.name.localeCompare(b.name) : filters.sort === "deadline" ? (programDeadline(a)?.match(/\d{4}[.-]\d{2}[.-]\d{2}/)?.[0].replaceAll(".", "-") ?? "9999").localeCompare(programDeadline(b)?.match(/\d{4}[.-]\d{2}[.-]\d{2}/)?.[0].replaceAll(".", "-") ?? "9999") : b.verified.localeCompare(a.verified) || Number(!!b.featured) - Number(!!a.featured));
  const totalPages = Math.max(1, Math.ceil(visible.length / 6)), page = Math.min(totalPages, Math.max(1, Number.parseInt(filters.page) || 1)), start = (page - 1) * 6;
  const updated = resources.map(r => r.verified.match(/\d{4}[.-]\d{2}[.-]\d{2}/)?.[0] ?? "").sort().at(-1);
  function select(key: keyof Filters, title: string, options: [string, string][], icon: "people" | "building" | "layers" | "money" | "calendar") { return <label className="program-filter"><CardFactIcon kind={icon}/><span className="sr-only">{title}</span><select aria-label={title} value={filters[key]} onChange={e => update({ [key]: e.target.value })}><option value="all">{title}</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>; }
  return <div className="programs-content">
    <section className="programs-hero"><div className="programs-intro"><p className="programs-eyebrow">BUILD ANYWHERE.<span> GO </span>FURTHER.</p><h1>Open Programs</h1><h2>{t("找到真正适合你的创业计划", "Find the right program for your next chapter")}</h2><p className="programs-description">{t("全球精选 Accelerator、Founder Program、创业课程与技术资源。", "Selected accelerators, founder programs, startup courses and technology support.")}<br/>{t("按照创业阶段、地区、资金和申请状态，发现最适合你的机会。", "Explore by stage, location, support and application status.")}</p>
    <label className="programs-search"><SearchIcon/><span className="sr-only">{t("搜索计划", "Search programs")}</span><input type="search" value={filters.q} onChange={e => update({ q: e.target.value })} placeholder={t("搜索计划、机构、城市或关键词…", "Search programs, organizations, cities or keywords…")}/><SearchIcon/></label>
    <div className="programs-status-tabs" aria-label={t("申请状态", "Application status")}>{["all", "open", "closing", "rolling"].map(id => <button key={id} type="button" aria-pressed={filters.status === id} onClick={() => update({ status: id })}>{id === "all" ? t("全部", "All") : statusCopy[id as ProgramStatus][en ? 1 : 0]} <span>{candidates.filter(r => matchesStatus(r, id)).length}</span></button>)}</div>
    <details className="programs-guide"><summary><span>i</span>{t("不知道怎么选？", "Not sure where to start?")} <b>{t("查看选择指南", "Selection guide")} →</b></summary><p>{t("申请与参加条件：先确认创业阶段、所在地和投入周期，再核对资金、股权及到场要求。当前窗口待核验的计划，请先查看详情中的官方来源。", "Check your stage, location and time commitment first, then funding, equity and attendance requirements. Verify application windows through the official sources in each brief.")}</p></details></div>
    <div className="programs-hero-art"><img width="1536" height="1024" decoding="async" fetchPriority="high" src="/programs/founder-mountains.webp" alt={t("登山者眺望远方群山", "A hiker looking across distant mountain ranges")}/><div className="programs-art-copy"><p>More<br/>Founders<br/>A Brighter<br/>Tomorrow</p><i/><small>GLOBAL OPPORTUNITIES<br/>REAL IMPACT</small></div></div></section>
    <section className="programs-directory" aria-label={t("资源列表", "Program directory")}><div className="programs-directory-heading"><h2>{visible.length} {t("个精选计划", "curated programs")}</h2><p>{t("最近更新", "Latest review")} {updated}</p></div>
    <div className="programs-filterbar">{select("stage", t("创业阶段", "Founder stage"), [["idea", t("想法探索", "Idea")], ["validation", t("产品验证", "Validation")], ["traction", t("增长与融资", "Traction")], ["growth", t("扩张", "Growth")]], "people")}{select("region", t("地区", "Location"), finderRegions.map(r => [r.id, en ? r.en : r.zh]), "building")}{select("kind", t("计划类型", "Program type"), [...new Set(resources.map(r => r.kind))].map(k => [k, en ? getEnglishResource(resources.find(r => r.kind === k)!.slug)?.kind ?? k : k]), "layers")}{select("funding", t("资金支持", "Funding support"), [["cash", t("已列投资 / 资助", "Documented investment / grants")], ["credits", t("云资源与额度", "Cloud resources / credits")], ["unspecified", t("金额未统一列明", "Amount not specified")]], "money")}{select("format", t("参与方式", "Participation"), [["online", t("在线", "Online")], ["onsite", t("线下", "Onsite")], ["hybrid", t("混合", "Hybrid")], ["unspecified", t("按项目核对", "Check each program")]], "calendar")}<label className="programs-sort">{t("排序", "Sort")}<select aria-label={t("排序", "Sort")} value={filters.sort} onChange={e => update({ sort: e.target.value })}><option value="updated">{t("最近更新", "Latest review")}</option><option value="deadline">{t("申请截止", "Deadline")}</option><option value="name">{t("名称", "Name")}</option></select></label></div>
    {unavailable && <p role="status">{t("社区新增计划暂时无法加载，已有档案仍可使用。", "Community additions are temporarily unavailable; curated briefs remain accessible.")}</p>}
    <div className="programs-grid">{visible.slice(start, start + 6).map(resource => { const copy = en ? getEnglishResource(resource.slug) ?? resource : resource, status = programStatus(resource, now), href = resource.detailPath || `${base}/resources/${resource.slug}`; const deadline = programDeadline(copy as Resource); const facts = [{ icon: "people" as const, label: t("适合", "Best for"), value: programHighlight(copy.highlights, /适合|主体|stage|applicant/i, copy.bestFor[0] || t("查看参与条件", "See eligibility")) }, { icon: "money" as const, label: t("资金 / 支持", "Funding / support"), value: programHighlight(copy.highlights, /资金|投资|资助|额度|funding|investment|grant|credits/i, t("按官方条款核对", "Check official terms")) }, { icon: "calendar" as const, label: t("周期", "Duration"), value: programHighlight(copy.highlights, /周期|duration|commitment/i, t("按具体项目核对", "Check each program")) }, { icon: "building" as const, label: t("地点", "Location"), value: programHighlight(copy.highlights, /地点|范围|location|coverage/i, copy.location) }]; return <article className="program-card" key={resource.slug}>
      {resource.featured && <span className="program-pick">PIONEER PICK</span>}<div className="program-card-top"><ProgramLogo slug={resource.slug} name={resource.name}/><div><h3><Link href={href}>{resource.name}</Link></h3><p>{copy.kind} · {copy.location}</p></div><span className={`program-badge ${status}`}>● {statusCopy[status][en ? 1 : 0]}</span></div>
      <div className="program-card-main"><div><p>{copy.description}</p><div className="program-tags">{copy.tags.slice(0, 3).map(tag => <span key={tag}>{tag}</span>)}</div></div><aside><small>APPLICATION</small><strong>{deadline || (status === "rolling" ? "Rolling" : t("按批次核对", "By program"))}</strong><span>{status === "review" ? t("当前窗口需重新核验", "Recheck the current window") : status === "archived" ? t("查看下一批次", "Check the next edition") : copy.timing}</span></aside></div>
      <div className="program-facts">{facts.map(f => <div key={f.label}><CardFactIcon kind={f.icon}/><div><small>{f.label}</small><span>{f.value}</span></div></div>)}</div>
      <div className="program-take"><span>PIONEER TAKE</span><p>{copy.editorialNote}</p></div><div className="program-card-footer"><small>{en ? `Reviewed ${resource.verified.match(/\d{4}[.-]\d{2}[.-]\d{2}/)?.[0] ?? "—"}` : resource.verified} · Pioneer</small><div><SaveResource slug={resource.slug} lang={lang}/><Link href={href} aria-label={`${t("查看", "Explore")} ${resource.name}`}>→</Link></div></div></article>; })}</div>
    {!visible.length && <div className="programs-empty"><h3>{t("没有匹配的计划", "No matching programs")}</h3><p>{t("试试减少筛选条件，或搜索其他城市与关键词。", "Try fewer filters or another city or keyword.")}</p><button type="button" onClick={() => update(initial)}>{t("重置筛选", "Reset filters")}</button></div>}
    <nav className="programs-pagination" aria-label={t("计划分页", "Program pages")}><small>{visible.length ? `${start + 1}–${Math.min(start + 6, visible.length)}` : "0"} / {visible.length}</small><button disabled={page === 1} onClick={() => update({ page: String(page - 1) }, false)} aria-label={t("上一页", "Previous page")}>‹</button>{Array.from({ length: totalPages }, (_, i) => i + 1).filter(p => p === 1 || p === totalPages || Math.abs(p - page) <= 2).map(p => <button key={p} aria-label={t(`第 ${p} 页`, `Page ${p}`)} aria-current={p === page ? "page" : undefined} onClick={() => update({ page: String(p) }, false)}>{p}</button>)}<button disabled={page === totalPages} onClick={() => update({ page: String(page + 1) }, false)} aria-label={t("下一页", "Next page")}>›</button></nav></section>
    <ProgramSignup lang={lang}/>
  </div>;
}
function ProgramSignup({ lang }: { lang: "zh" | "en" }) {
  const en = lang === "en", [email, setEmail] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [done, setDone] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setMessage(""); const website = new FormData(e.currentTarget).get("website"); try { const response = await fetch("/api/newsletter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, language: lang, sourcePath: en ? "/en/programs" : "/programs", website }) }); const result = await response.json(); if (!response.ok) throw new Error("registration"); setDone(true); setMessage(result.deliveryEnabled ? (en ? "Interest registered. Manage your notification preferences in your workspace." : "已登记通知意向，可在工作台管理通知偏好。") : (en ? "Interest registered. Email delivery is not enabled yet." : "已登记通知意向，邮件发送尚未启用。")); } catch { setMessage(en ? "Registration failed. Please try again." : "登记失败，请稍后重试。"); } finally { setBusy(false); } }
  return <section className="programs-newsletter"><div><p className="programs-eyebrow">WEEKLY OPPORTUNITY SIGNAL</p><h2>{en ? "Find your next founder opportunity." : "不想错过真正值得申请的创业机会？"}</h2><p>{en ? "Register your interest in future program and event updates." : "登记创业计划与活动通知意向，发送安排以工作台设置为准。"}</p></div><div><form onSubmit={submit}><label className="sr-only" htmlFor="program-email">Email</label><input id="program-email" type="email" required placeholder="your@email.com" value={email} onChange={e => setEmail(e.target.value)} disabled={done}/><input name="website" tabIndex={-1} autoComplete="off" className="programs-honeypot" aria-hidden="true"/><button type="submit" disabled={busy || done}>{done ? (en ? "Registered" : "已登记") : busy ? "…" : (en ? "Register interest →" : "登记通知意向 →")}</button></form><p role="status">{message || (en ? "Your existing preferences and opt-outs are preserved." : "保护你的隐私，并保留现有通知与退订设置。")}</p></div><em>Better<br/>Founders<br/>A Brighter<br/>Tomorrow</em></section>;
}
