"use client";
import { PioneerBrand } from "./PioneerBrand";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {usePathname} from "next/navigation";
import {AudienceCount} from "./AudienceCounter";
function Icon({kind}:{kind:"search"|"bookmark"|"user"}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==="search"?<><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></>:kind==="bookmark"?<path d="M6 3h12v18l-6-4-6 4z"/>:<><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></>}</svg>;}
export function SiteNavigation({lang,languageHref}:{lang:"zh"|"en";languageHref?:string}){
 const en=lang==="en",prefix=en?"/en":"",path=usePathname();
 const [show,setShow]=useState(true),[query,setQuery]=useState("");const dialog=useRef<HTMLDialogElement>(null),search=useRef<HTMLInputElement>(null);
 const links=[["programs",en?"Programs":"开放计划"],["organizations",en?"Organizations":"创业机构"],["events",en?"Events":"创业活动"],["startups",en?"Projects":"创业项目"]];
 function openSearch(){const input=document.getElementById("resource-search");if(input){input.focus();input.scrollIntoView({block:"center",behavior:"smooth"});}else{dialog.current?.showModal();search.current?.focus();}}
 useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();const input=document.getElementById("resource-search");if(input){input.focus();input.scrollIntoView({block:"center"});}else{dialog.current?.showModal();search.current?.focus();}}};window.addEventListener("keydown",shortcut);return()=>window.removeEventListener("keydown",shortcut);},[]);
 function submit(event:FormEvent){event.preventDefault();window.location.assign(`${prefix||"/"}${prefix?"/":""}?q=${encodeURIComponent(query.trim())}#resources`);}
 const current=(href:string)=>path===href||path?.startsWith(href+"/")?"page" as const:undefined;
 return <>{show&&<div className="design-announcement"><span>{en?"Curated resources are live":"站内整理已上线"}</span><p>{en?"":"已有 "}<AudienceCount/> {en?"visitors have explored Pioneer":"位访客来过 Pioneer"}</p><button type="button" aria-label={en?"Dismiss announcement":"关闭公告"} onClick={()=>setShow(false)}>×</button></div>}<div className="site-navigation"><header className="design-header design-width" data-design-system="pioneer"><a className="design-brand" href={prefix||"/"} aria-label={en?"Pioneer home":"Pioneer 首页"}><PioneerBrand/></a><nav aria-label={en?"Primary navigation":"主导航"}><details className="discover-menu"><summary>{en?"Discover":"发现"} <span aria-hidden="true">⌄</span></summary><div>{links.map(([slug,label])=><a href={`${prefix}/${slug}`} key={slug} aria-current={current(`${prefix}/${slug}`)}>{label}</a>)}<div className="mobile-menu-links">{[["weekly",en?"Weekly":"本周机会"],["knowledge",en?"Founder guides":"创业指南"],["community",en?"Community":"社区"],["submit",en?"Submit resource":"提交资源"]].map(([slug,label])=><a href={`${prefix}/${slug}`} key={slug}>{label}</a>)}</div></div></details>{[["weekly",en?"Weekly":"本周机会"],["knowledge",en?"Founder guides":"创业指南"],["community",en?"Community":"社区"]].map(([slug,label])=><a href={`${prefix}/${slug}`} key={slug} aria-current={current(`${prefix}/${slug}`)}>{label}</a>)}</nav><div className="design-header-actions"><button type="button" className="header-search" onClick={openSearch} aria-label={en?"Search resources":"搜索资源"}><Icon kind="search"/><span>{en?"Resources, programs, events…":"搜索国家、机构、计划、活动…"}</span><kbd>⌘ K</kbd></button><a className="header-bookmark" href={`${prefix}/workspace`} aria-label={en?"Saved resources":"资源清单"}><Icon kind="bookmark"/></a><a className="workspace-link" href={`${prefix}/workspace`} aria-current={current(`${prefix}/workspace`)}>{en?"My workspace":"我的工作台"}</a><a className="account-link" href={`${prefix}/login`} aria-label={en?"Account":"账号"} aria-current={current(`${prefix}/login`)}><Icon kind="user"/></a><a className="design-language" href={languageHref??(en?(path?.replace(/^\/en(?=\/|$)/,"")||"/"):`/en${path==="/"?"":path??""}`)} lang={en?"zh":"en"}>{en?"中文":"EN"}</a></div></header></div><dialog ref={dialog} className="site-search-dialog" aria-labelledby="site-search-title"><div className="site-search-heading"><h2 id="site-search-title">{en?"Search Pioneer":"搜索 Pioneer"}</h2><button type="button" onClick={()=>dialog.current?.close()} aria-label={en?"Close search":"关闭搜索"}>×</button></div><form onSubmit={submit}><label htmlFor="site-search-input">{en?"Country, city, program or idea":"国家、城市、计划或创业方向"}</label><div><input ref={search} id="site-search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder={en?"What are you looking for?":"你在寻找什么？"}/><button type="submit">{en?"Search":"搜索"}</button></div></form></dialog></>;
}
