import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
const origin = process.env.PIONEER_PREVIEW_URL ?? 'http://localhost:3000';
assert.ok(['localhost', '127.0.0.1'].includes(new URL(origin).hostname), 'Local preview only');
const agent = `Moderation-local-${randomUUID()}`;
const headers = { origin, 'content-type': 'application/json', 'user-agent': agent };
const admin = { ...headers, 'oai-authenticated-user-id': 'mail-admin-test', 'oai-authenticated-user-email': process.env.PIONEER_TEST_ADMIN_EMAIL ?? 'mail-admin-preview@example.org' };
const post = (path, body, identity = headers) => fetch(`${origin}${path}`, { method: 'POST', headers: identity, body: JSON.stringify(body) });
const queue = async () => { const response = await fetch(`${origin}/api/admin/reviews`, { headers: admin }); assert.equal(response.status, 200); return response.json(); };
const receipt = async token => (await fetch(`${origin}/api/submissions?token=${token}`)).json();
const note = 'Verified the local controlled source fixture and checked its supplied data.';
test('actual D1 moderation publishes bilingual pages, resolves corrections once and withdraws resubmitted ownership', async () => {
  const source = `https://pioneer-local-fixture.org/${randomUUID()}`;
  const payload = { resourceType: 'program', resourceName: `Audit resource ${randomUUID()}`, resourceUrl: source, location: 'Berlin', stage: 'validation', deadline: '2027-01-20', whyUseful: 'Controlled local fixture for checking the full founder contribution workflow.', submitterName: 'Local fixture', submitterEmail: 'local-private@example.org', relationship: 'community', language: 'en', idempotencyKey: randomUUID().replaceAll('-', '') };
  const submission = await post('/api/submissions', payload); assert.equal(submission.status, 201);
  const first = await submission.json(); assert.equal(first.status, 'pending');
  const row = (await queue()).submissions.find(row => row.review_token === first.reviewToken); assert.ok(row);
  const approve = id => post('/api/admin/reviews', { id, action: 'approve', note, officialConfirmed: true, sourceUrl: source, sourceTitle: 'Local controlled fixture', sourceExcerpt: 'Local fixture evidence, never a production resource recommendation.' }, admin);
  const withdraw = id => post('/api/admin/reviews', { id, action: 'withdraw', note }, admin);
  assert.equal((await approve(row.id)).status, 200);
  const published = await receipt(first.reviewToken); assert.equal(published.status, 'approved');
  for (const prefix of ['', '/en']) {
    const response = await fetch(`${origin}${prefix}${published.resourcePath}`); assert.equal(response.status, 200);
    const html = await response.text(); assert.ok(html.includes(payload.resourceName)); assert.ok(!html.includes(payload.submitterEmail));
  }
  const slug = published.resourcePath.split('/').at(-1);
  assert.equal((await post('/api/reports', { resourceKey: slug, reason: 'incorrect', details: 'Local controlled correction fixture to check durable resolution.' })).status, 201);
  const report = (await queue()).reports.find(row => row.resource_key === slug); assert.ok(report);
  const resolve = id => post('/api/admin/reviews', { id, action: 'resolve-report', note }, admin);
  assert.equal((await resolve(2147483647)).status, 404);
  assert.equal((await resolve(report.id)).status, 200);
  assert.equal((await resolve(report.id)).status, 409);
  assert.equal((await queue()).reports.find(row => row.id === report.id).status, 'resolved');
  assert.equal((await withdraw(row.id)).status, 200);
  assert.equal((await receipt(first.reviewToken)).status, 'rejected');
  assert.equal((await fetch(`${origin}${published.resourcePath}`)).status, 404);
  const resubmission = await post('/api/submissions', { ...payload, resourceName: `${payload.resourceName} updated`, location: 'Paris', stage: 'traction', deadline: '2027-02-20', idempotencyKey: randomUUID().replaceAll('-', '') }); assert.equal(resubmission.status, 201);
  const second = await resubmission.json(); assert.equal(second.status, 'pending');
  const secondRow = (await queue()).submissions.find(row => row.review_token === second.reviewToken); assert.ok(secondRow);
  assert.equal((await approve(secondRow.id)).status, 200);
  assert.equal((await receipt(second.reviewToken)).resourcePath, published.resourcePath);
  let listing = (await (await fetch(`${origin}/api/community`)).json()).resources.find(row => row.slug === slug);
  assert.equal(listing.submission_id, secondRow.id); assert.equal(listing.location, 'Paris'); assert.equal(listing.stage, 'traction'); assert.equal(listing.deadline, '2027-02-20');
  assert.equal((await withdraw(row.id)).status, 200);
  assert.equal((await fetch(`${origin}${published.resourcePath}`)).status, 200);
  assert.equal((await withdraw(secondRow.id)).status, 200);
  assert.equal((await fetch(`${origin}${published.resourcePath}`)).status, 404);
  listing = (await (await fetch(`${origin}/api/community`)).json()).resources.find(row => row.slug === slug); assert.equal(listing, undefined);
});
